# BaseLine Logit, self training only model seed 2023, How well does self-training model label using unseen text file? unlabel_percentage = 0.3

In [ ]:
from datasets import load_dataset
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.semi_supervised import SelfTrainingClassifier
import pandas as pd
import joblib

# https://www.codecademy.com/resources/docs/sklearn/self-training
# https://www.altexsoft.com/blog/semi-supervised-learning/
# https://scikit-learn.org/stable/modules/semi_supervised.html
# This self-training implementation is based on Yarowsky’s [1] algorithm.
# https://towardsdatascience.com/self-training-classifier-how-to-make-any-algorithm-behave-like-a-semi-supervised-one-2958e7b54ab7/

review_data = pd.read_csv("/Users/apple/Documents/GitHub/Steam-Market-Data-ML/unlabeled_reviews.csv")


print(review_data["review_comment"].isna().sum())
review_data["review_comment"] = review_data["review_comment"].fillna("") 
review_data["recommend"] = review_data["recommend"].map({"Recommended": 1, "Not Recommended": 0})

vectorizer = TfidfVectorizer()

review_X = vectorizer.fit_transform(review_data["review_comment"])  # Convert text to TF-IDF features

# Array representing the labels. Unlabeled samples should have the label -1.
review_y = review_data["recommend"].fillna(-1)


# print(vectorizer.get_feature_names_out())  # Shows vocabulary
review_X_train, review_X_test, review_y_train, review_y_test = train_test_split(review_X, review_y, test_size=0.2, random_state=2023)

print(f"count for missing data {len(review_y_train[review_y_train==-1])}")
print(f"count for labeled data {len(review_y_train[review_y_train!=-1])}")
print(f"count for missing data_test {len(review_y_test [review_y_test ==-1])}")
print(f"count for labeled data_Test {len(review_y_test [review_y_test !=-1])}")


logit_review_model = LogisticRegression()





self_training_logit_model = SelfTrainingClassifier(logit_review_model,verbose=True)

self_training_logit_model.fit(review_X_train, review_y_train)


print(sum(review_y_pred==-1))
print(sum(review_y_test==-1))

# create a mask
mask = review_y_test != -1 
review_X_test =   review_X_test[mask]
review_y_test =  review_y_test[mask]


review_y_pred = self_training_logit_model.predict(review_X_test)


# print(review_X_train.shape[0])
# This metaestimator allows a given supervised classifier to function as a semi-supervised classifier, allowing it to learn from unlabeled data. 
# It does this by iteratively predicting pseudo-labels for the unlabeled data and adding them to the training set.

accuracy = accuracy_score(review_y_test , review_y_pred)
precision = precision_score(review_y_test , review_y_pred ,average='macro')
recall = recall_score(review_y_test, review_y_pred ,average='macro')


print("\nEvaluation Results on Test Data:")
print(f"Accuracy:  {accuracy}")
print(f"Precision: {precision}")
print(f"Recall:    {recall}")
print(f"Accuracy: {accuracy:.4f}")


joblib.dump(self_training_logit_model, "base_logistic_model.pkl")
print("\nModel saved successfully.")

1
count for missing data 20073
count for labeled data 46744
count for missing data_test 4983
count for labeled data_Test 11722
End of iteration 1, added 14534 new labels.
End of iteration 2, added 803 new labels.
End of iteration 3, added 143 new labels.
End of iteration 4, added 77 new labels.
End of iteration 5, added 10 new labels.
End of iteration 6, added 13 new labels.
End of iteration 7, added 1 new labels.
End of iteration 8, added 7 new labels.
End of iteration 9, added 23 new labels.
End of iteration 10, added 16 new labels.
0
4983

Evaluation Results on Test Data:
Accuracy:  0.8544616959563215
Precision: 0.8474009780276295
Recall:    0.8120987990824307
Accuracy: 0.8545

Model saved successfully.

This tells us how the model is able to predict labels it has not seen before but does not tell us how accurate the model actually impute the data set necessarly

The data for random seed 2025 seem to very specifically yeild 0 as an accuracy result seems like I randomly pick the worse training data for it. Since logistic is fast to train I decided to make some random seed and average it

# BaseLine Logit, self training only model seed 2023, How well does self-training model impute the entire file. Not implmented yet

Metrics entire dataset,  All prediction/total lableled data

In [ ]:
from datasets import load_dataset
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.semi_supervised import SelfTrainingClassifier
import pandas as pd
import joblib

# https://www.codecademy.com/resources/docs/sklearn/self-training
# https://www.altexsoft.com/blog/semi-supervised-learning/
# https://scikit-learn.org/stable/modules/semi_supervised.html
# This self-training implementation is based on Yarowsky’s [1] algorithm.
# https://towardsdatascience.com/self-training-classifier-how-to-make-any-algorithm-behave-like-a-semi-supervised-one-2958e7b54ab7/

review_data = pd.read_csv("/Users/apple/Documents/GitHub/Steam-Market-Data-ML/unlabeled_reviews.csv")


print(review_data["review_comment"].isna().sum())
review_data["review_comment"] = review_data["review_comment"].fillna("") 
review_data["recommend"] = review_data["recommend"].map({"Recommended": 1, "Not Recommended": 0})

vectorizer = TfidfVectorizer()

review_X = vectorizer.fit_transform(review_data["review_comment"])  # Convert text to TF-IDF features

# Array representing the labels. Unlabeled samples should have the label -1.
review_y = review_data["recommend"].fillna(-1)


# print(vectorizer.get_feature_names_out())  # Shows vocabulary
# review_X_train, review_X_test, review_y_train, review_y_test = train_test_split(review_X, review_y, test_size=0.2, random_state=2023)

# print(f"count for missing data {len(review_y_train[review_y_train==-1])}")
# print(f"count for labeled data {len(review_y_train[review_y_train!=-1])}")
# print(f"count for missing data_test {len(review_y_test [review_y_test ==-1])}")
# print(f"count for labeled data_Test {len(review_y_test [review_y_test !=-1])}")


logit_review_model = LogisticRegression()



def train_sk_single_model(dataset,model)
# dataset should be a tuple here 
    X, y = dataset
    model.fit(train_x, train_y,)
    return model


def train_



self_training_logit_model = SelfTrainingClassifier(logit_review_model,verbose=True)

# fit using the entire data set
self_training_logit_model.fit(review_X , review_y)



#-------making the test data file from full data


review_data_test = pd.read_csv("/Users/apple/Documents/GitHub/Steam-Market-Data-ML/cleaned_reviews.csv")


print(review_data_test ["review_comment"].isna().sum())
review_data_test ["review_comment"] = review_data_test ["review_comment"].fillna("") 
review_data_test ["recommend"] = review_data_test ["recommend"].map({"Recommended": 1, "Not Recommended": 0})



review_X_test= vectorizer.transform(review_data_test ["review_comment"])  # Convert text to TF-IDF features
review_y_test = review_data_test["recommend"]


# review_X_test is the same as review_X so we are just retriveving the predicted label

review_y_pred = self_training_logit_model.predict(review_X_test)


# print(review_X_train.shape[0])
# This metaestimator allows a given supervised classifier to function as a semi-supervised classifier, allowing it to learn from unlabeled data. 
# It does this by iteratively predicting pseudo-labels for the unlabeled data and adding them to the training set.

accuracy = accuracy_score(review_y_test, review_y_pred)
precision = precision_score(review_y_test, review_y_pred ,average='macro')
recall = recall_score(review_y_test, review_y_pred ,average='macro')


print("\nEvaluation Results on Test Data:")
print(f"Accuracy:  {accuracy}")
print(f"Precision: {precision}")
print(f"Recall:    {recall}")
print(f"Accuracy: {accuracy:.4f}")

1
End of iteration 1, added 18336 new labels.
End of iteration 2, added 981 new labels.
End of iteration 3, added 209 new labels.
End of iteration 4, added 49 new labels.
End of iteration 5, added 20 new labels.
End of iteration 6, added 22 new labels.
End of iteration 7, added 8 new labels.
End of iteration 8, added 53 new labels.
End of iteration 9, added 28 new labels.
End of iteration 10, added 5 new labels.
1

Evaluation Results on Test Data:
Accuracy:  0.8732310050046694
Precision: 0.8695981871592748
Recall:    0.8361131558801127
Accuracy: 0.8732

# Evaluatiing on only unlabeled data

Unlabeled prediction/unlableled data

Using the unlabeled data X as input to predict how many are labeled correctly

In [8]:

review_data_test = pd.read_csv("/Users/apple/Documents/GitHub/Steam-Market-Data-ML/cleaned_reviews.csv")


print(review_data_test ["review_comment"].isna().sum())
review_data_test ["review_comment"] = review_data_test ["review_comment"].fillna("") 
review_data_test ["recommend"] = review_data_test ["recommend"].map({"Recommended": 1, "Not Recommended": 0})


review_X_test= vectorizer.transform(review_data_test ["review_comment"])  # Convert text to TF-IDF features
review_y_test = review_data_test["recommend"]


# only the unlabled data
mask = review_y == -1 
review_X_test =   review_X_test[mask]
review_y_test =  review_y_test[mask]


review_y_pred = self_training_logit_model.predict(review_X_test)


# print(review_X_train.shape[0])
# This metaestimator allows a given supervised classifier to function as a semi-supervised classifier, allowing it to learn from unlabeled data. 
# It does this by iteratively predicting pseudo-labels for the unlabeled data and adding them to the training set.

accuracy = accuracy_score(review_y_test, review_y_pred)
precision = precision_score(review_y_test, review_y_pred ,average='macro')
recall = recall_score(review_y_test, review_y_pred ,average='macro')


print("\nEvaluation Results on Test Data:")
print(f"Accuracy:  {accuracy}")
print(f"Precision: {precision}")
print(f"Recall:    {recall}")
print(f"Accuracy: {accuracy:.4f}")

1

Evaluation Results on Test Data:
Accuracy:  0.8614303959131545
Precision: 0.8557344357789043
Recall:    0.8229421484510033
Accuracy: 0.8614

  # Implementation with random f to new data

In [33]:
from datasets import load_dataset
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.semi_supervised import SelfTrainingClassifier
import pandas as pd
import joblib

# https://www.codecademy.com/resources/docs/sklearn/self-training

# https://scikit-learn.org/stable/modules/semi_supervised.html
# This self-training implementation is based on Yarowsky’s [1] algorithm.
# https://towardsdatascience.com/self-training-classifier-how-to-make-any-algorithm-behave-like-a-semi-supervised-one-2958e7b54ab7/

review_data = pd.read_csv("/Users/apple/Documents/GitHub/Steam-Market-Data-ML/unlabeled_reviews.csv")


print(review_data["review_comment"].isna().sum())
review_data["review_comment"] = review_data["review_comment"].fillna("") 
review_data["recommend"] = review_data["recommend"].map({"Recommended": 1, "Not Recommended": 0})

vectorizer = TfidfVectorizer()

review_X = vectorizer.fit_transform(review_data["review_comment"])  # Convert text to TF-IDF features

# Array representing the labels. Unlabeled samples should have the label -1.
review_y = review_data["recommend"].fillna(-1)


# print(vectorizer.get_feature_names_out())  # Shows vocabulary
review_X_train, review_X_test, review_y_train, review_y_test = train_test_split(review_X, review_y, test_size=0.2, random_state=2023)


random_forest_model = RandomForestClassifier(n_estimators=30, random_state=2023)



self_training_logit_model = SelfTrainingClassifier(random_forest_model,verbose=True)

self_training_logit_model.fit(review_X_train, review_y_train)

mask = review_y_test != -1 
review_X_test =   review_X_test[mask]
review_y_test =  review_y_test[mask]

review_y_pred = self_training_logit_model.predict(review_X_test)

# print(review_X_train.shape[0])
# This metaestimator allows a given supervised classifier to function as a semi-supervised classifier, allowing it to learn from unlabeled data. 
# It does this by iteratively predicting pseudo-labels for the unlabeled data and adding them to the training set.

accuracy = accuracy_score(review_y_test, review_y_pred )
precision = precision_score(review_y_test, review_y_pred ,average='macro')
recall = recall_score(review_y_test, review_y_pred ,average='macro')


print("\nEvaluation Results on Test Data:")
print(f"Accuracy:  {accuracy}")
print(f"Precision: {precision}")
print(f"Recall:    {recall}")
print(f"Accuracy: {accuracy:.4f}")


joblib.dump(self_training_logit_model, "selftrain_noboot_rf_model.pkl")
print("\nModel saved successfully.")


with open('evaluation_results_selftrain_noboot_rf_model.txt', 'w') as f:
    f.write(f"Accuracy after fine-tuning: {accuracy:.4f}\n")
    f.write(f"Precision: {precision:.4f}\n")
    f.write(f"Recall: {recall:.4f}\n")

1
End of iteration 1, added 11663 new labels.
End of iteration 2, added 1743 new labels.
End of iteration 3, added 931 new labels.
End of iteration 4, added 601 new labels.
End of iteration 5, added 451 new labels.
End of iteration 6, added 283 new labels.
End of iteration 7, added 256 new labels.
End of iteration 8, added 208 new labels.
End of iteration 9, added 169 new labels.
End of iteration 10, added 162 new labels.

Evaluation Results on Test Data:
Accuracy:  0.8244326906671217
Precision: 0.8159755537925456
Recall:    0.7696756895909413
Accuracy: 0.8244

Model saved successfully.

# Random forest evluation

Metrics entire dataset,  All prediction/total lableled data

In [ ]:
from datasets import load_dataset
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.semi_supervised import SelfTrainingClassifier
import pandas as pd
import joblib

# https://www.codecademy.com/resources/docs/sklearn/self-training
# https://www.altexsoft.com/blog/semi-supervised-learning/
# https://scikit-learn.org/stable/modules/semi_supervised.html
# This self-training implementation is based on Yarowsky’s [1] algorithm.
# https://towardsdatascience.com/self-training-classifier-how-to-make-any-algorithm-behave-like-a-semi-supervised-one-2958e7b54ab7/

review_data = pd.read_csv("/Users/apple/Documents/GitHub/Steam-Market-Data-ML/unlabeled_reviews.csv")


print(review_data["review_comment"].isna().sum())
review_data["review_comment"] = review_data["review_comment"].fillna("") 
review_data["recommend"] = review_data["recommend"].map({"Recommended": 1, "Not Recommended": 0})

vectorizer = TfidfVectorizer()

review_X = vectorizer.fit_transform(review_data["review_comment"])  # Convert text to TF-IDF features

# Array representing the labels. Unlabeled samples should have the label -1.
review_y = review_data["recommend"].fillna(-1)


# print(vectorizer.get_feature_names_out())  # Shows vocabulary
# review_X_train, review_X_test, review_y_train, review_y_test = train_test_split(review_X, review_y, test_size=0.2, random_state=2023)

# print(f"count for missing data {len(review_y_train[review_y_train==-1])}")
# print(f"count for labeled data {len(review_y_train[review_y_train!=-1])}")
# print(f"count for missing data_test {len(review_y_test [review_y_test ==-1])}")
# print(f"count for labeled data_Test {len(review_y_test [review_y_test !=-1])}")


random_forest_model = RandomForestClassifier(n_estimators=30, random_state=2023)





self_training_logit_model = SelfTrainingClassifier(random_forest_model ,verbose=True)

self_training_logit_model.fit(review_X , review_y)



#-------making the test data file from full data


review_data_test = pd.read_csv("/Users/apple/Documents/GitHub/Steam-Market-Data-ML/cleaned_reviews.csv")


print(review_data_test ["review_comment"].isna().sum())
review_data_test ["review_comment"] = review_data_test ["review_comment"].fillna("") 
review_data_test ["recommend"] = review_data_test ["recommend"].map({"Recommended": 1, "Not Recommended": 0})

vectorizer = TfidfVectorizer()

review_X_test= vectorizer.fit_transform(review_data_test ["review_comment"])  # Convert text to TF-IDF features
review_y_test = review_data_test["recommend"]




review_y_pred = self_training_logit_model.predict(review_X_test)


# print(review_X_train.shape[0])
# This metaestimator allows a given supervised classifier to function as a semi-supervised classifier, allowing it to learn from unlabeled data. 
# It does this by iteratively predicting pseudo-labels for the unlabeled data and adding them to the training set.

accuracy = accuracy_score(review_y_test, review_y_pred)
precision = precision_score(review_y_test, review_y_pred ,average='macro')
recall = recall_score(review_y_test, review_y_pred ,average='macro')


print("\nEvaluation Results on Test Data:")
print(f"Accuracy:  {accuracy}")
print(f"Precision: {precision}")
print(f"Recall:    {recall}")
print(f"Accuracy: {accuracy:.4f}")

1
count for missing data 20073
count for labeled data 46744
count for missing data_test 0
count for labeled data_Test 83522
End of iteration 1, added 14767 new labels.
End of iteration 2, added 2144 new labels.
End of iteration 3, added 1023 new labels.
End of iteration 4, added 704 new labels.
End of iteration 5, added 507 new labels.
End of iteration 6, added 359 new labels.
End of iteration 7, added 331 new labels.
End of iteration 8, added 276 new labels.
End of iteration 9, added 246 new labels.
End of iteration 10, added 202 new labels.
1

Evaluation Results on Test Data:
Accuracy:  0.9427456239074735
Precision: 0.9435867727562016
Recall:    0.9252796810941468
Accuracy: 0.9427

In [52]:

with open('evaluation_results_selftrain_noboot__fulldta_rf_model.txt', 'w') as f:
    f.write(f"Accuracy after fine-tuning: {accuracy:.4f}\n")
    f.write(f"Precision: {precision:.4f}\n")
    f.write(f"Recall: {recall:.4f}\n")

# only unlabeld

Unlabeled prediction/unlableled data

In [ ]:

review_data_test = pd.read_csv("/Users/apple/Documents/GitHub/Steam-Market-Data-ML/cleaned_reviews.csv")



print(review_data_test ["review_comment"].isna().sum())
review_data_test ["review_comment"] = review_data_test ["review_comment"].fillna("") 
review_data_test ["recommend"] = review_data_test ["recommend"].map({"Recommended": 1, "Not Recommended": 0})


review_X_test= vectorizer.fit_transform(review_data_test ["review_comment"])  # Convert text to TF-IDF features
review_y_test = review_data_test["recommend"]


# only the unlabled data
mask = review_y == -1 
review_X_test =   review_X_test[mask]
review_y_test =  review_y_test[mask]

review_y_pred = self_training_logit_model.predict(review_X_test)


# print(review_X_train.shape[0])
# This metaestimator allows a given supervised classifier to function as a semi-supervised classifier, allowing it to learn from unlabeled data. 
# It does this by iteratively predicting pseudo-labels for the unlabeled data and adding them to the training set.

accuracy = accuracy_score(review_y_test, review_y_pred)
precision = precision_score(review_y_test, review_y_pred ,average='macro')
recall = recall_score(review_y_test, review_y_pred ,average='macro')


print("\nEvaluation Results on Test Data:")
print(f"Accuracy:  {accuracy}")
print(f"Precision: {precision}")
print(f"Recall:    {recall}")
print(f"Accuracy: {accuracy:.4f}")

1

Evaluation Results on Test Data:
Accuracy:  0.838521711366539
Precision: 0.8337905730866886
Recall:    0.7895399069999248
Accuracy: 0.8385

In [2]:

def stat_bootstrap_df(data, num_samples=1000):
    """
    Perform bootstrapping with replacement using pandas to estimate the sampling distribution of a statistic.
    
    Parameters:
    - data: A pandas Series or DataFrame.
    - num_samples: The number of bootstrap samples to generate.

    Returns:
    - bootstrap_samples: A pandas Series containing bootstrap sample statistics.
    """
    # Ensure data is a pandas Series
    if isinstance(data, pd.DataFrame):
        data = data.squeeze()  # Converts DataFrame to Series if needed
    
    bootstrap_samples = []

    for _ in range(num_samples):
        # Generate a bootstrap sample by randomly sampling with replacement
        sample = data.sample(n=len(data), replace=True)
        # Calculate the statistic (e.g., mean)
        bootstrap_samples.append(sample)

    return pd.Series(bootstrap_samples)

# bert self trianing

In [5]:
import torch

if torch.backends.mps.is_available():
    print("MPS is available.")
else:
    print("MPS is NOT available.")

# Optional: Also check if it's built (important for some setups)
if torch.backends.mps.is_built():
    print("MPS backend is built into PyTorch.")
else:
    print("MPS backend is NOT built into PyTorch.")

MPS is available.
MPS backend is built into PyTorch.

In [ ]:
def get_predictions(model, data, batch_size=64):
    """ Get predictions on data for a classification model m returning predictions and true labels"""
    model.to("cpu")
    model.eval()
 
    all_predictions = []
    all_confidences = []
    
    if len(data['input_ids']) % batch_size != 0:
        num_batches = len(data['input_ids']) // batch_size + 1
    else:
        num_batches = len(data['input_ids']) // batch_size

    for i in tqdm(range(num_batches),desc= "Prediction Progress"):
        start_idx = i * batch_size
        end_idx = min((i + 1) * batch_size, len(data['input_ids'])) # prevent going out of bount input_ids has same size as attention mask should
        input_ids_batch = torch.tensor(data['input_ids'][start_idx:end_idx])
        attention_mask_batch = torch.tensor(data['attention_mask'][start_idx:end_idx])
        with torch.no_grad():  # Disable gradient computation for inference
            predictions = model(input_ids_batch, attention_mask=attention_mask_batch)
            logits = predictions.logits
            predictions = torch.argmax(logits, dim=-1) # make sure it is a ser
            probs = torch.nn.functional.softmax(logits, dim=-1) # return a proabiblity distribution
            max_probs, _ = torch.max(probs, dim=-1)
            
        all_confidences.append(max_probs)  # this tells us how confident we are with an value
        all_predictions.append(predictions)
        # print(predictions)
        # print("--------")
    # print(all_predictions)
    
    
    #Concatenate all batch predictions into one tensor since we currently have a list of lists
    all_predictions = torch.cat(all_predictions, dim=0)
    all_confidences = torch.cat(all_confidences, dim=0)
    
    return all_predictions , all_confidences


def self_training_loop(model, train_dataset, tokenizer, confidence_threshold=0.9, num_epochs=1, mode='unlabeled',threshold_mode = 'fix'):
    
    # still need to better develop still bad code since exit really randomly depend on the confidence_threshold which is not good for big data waiting for the final data point to set in
    
    
    data_collator = DataCollatorWithPadding(tokenizer) 
    training_args = TrainingArguments(
        num_train_epochs=num_epochs,      # Number of training epochs
    )

    
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,    # Training dataset   
        data_collator=data_collator,
    )
    
    #https://github.com/tqdm/tqdm#usage
    unlabeled_mask =  train_dataset["label"] == -1
    total_unlabeled = sum(label == -1 for label in train_dataset["label"])
    pbar = tqdm(total=total_unlabeled, desc="Unlabeled Samples Remaining")

    labeled_train_dataset = train_dataset.filter(lambda x: x["label"] != -1)
    trainer.train_dataset = labeled_train_dataset  # Update trainer with labeled dataset
    print(f"data: { labeled_train_dataset =}")
    # https://peps.python.org/pep-0289/
    print(sum(label == -1 for label in labeled_train_dataset["label"]))
    print("hello")
    trainer.train()

    while -1 in train_dataset["label"]:
        # trainer.train()
        predictions, confidences = get_predictions(model, train_dataset)
        
        if threshold_mode == 'fix':
            threshold_value = confidence_threshold
        elif threshold_mode == 'quantile':
            # this mode with too higih quantile does have converge issue
            threshold_value = torch.quantile(confidences, confidence_threshold).item()
        else:
            print("threshold mode not specified")

        print(confidences)
        print(predictions)
        print(len(train_dataset))
        print("------------------------")
        if mode == 'unlabeled':
        # we might want to make distinction here is the train_dataset label only or etc
        #  It allows you to apply a processing function to each example in a dataset, independently or in batches. This function can even create new rows and columns.
        # https://huggingface.co/docs/datasets/en/process
            condition_met_indices = [] # this is just here to keep track of the pesudo labeled added per iteration if needed
            # example here is each row
            def update_labels(example, idx):
                # Update labels for unlabeled data only, if confidence is above the threshold
                if example['label'] == -1 and confidences[idx] >= threshold_value:
                    example['label'] = predictions[idx]
                    condition_met_indices.append(idx)
                return example

            # Use .map() to apply the updates to all examples where the condition is met
            train_dataset = train_dataset.map(update_labels, with_indices=True)
            print(f"Indices where the condition was met: {condition_met_indices}")
                  

        # untested yet !!!!!!!
        elif mode == "all":
            def update_labels_all(example, idx):
                if confidences[idx] >= threshold_value:
                    example['label'] = predictions[idx]
                    condition_met_indices.append(idx)
                return example

            train_dataset = train_dataset.map(update_labels_all, with_indices=True)
            print(f"Indices where the condition was met: {condition_met_indices}")
                    
        # Update trainer with the latest training data
        pbar.update(len(condition_met_indices))
        trainer.train_dataset = train_dataset
        trainer.train()
            
        if -1 not in train_dataset["label"]:
          print("All labels are filled. Stopping training.")
          break
        
    return model, train_dataset

# testing for 5000 sample

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score
from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments
from sklearn.feature_extraction.text import TfidfVectorizer
from transformers import DataCollatorWithPadding
import torch
from datasets import Dataset
from trl import IterativeSFTTrainer
from tqdm import tqdm


# We are still in datafre

review_data = pd.read_csv("/Users/apple/Documents/GitHub/Steam-Market-Data-ML/unlabeled_reviews.csv",nrows=5000)

print(review_data["review_comment"].isna().sum())
review_data["review_comment"] = review_data["review_comment"].fillna("") 
review_data["recommend"] = review_data["recommend"].map({"Recommended": 1, "Not Recommended": 0})



# vectorizer = TfidfVectorizer()

# review_X = vectorizer.fit_transform(review_data["review_comment"])  # Convert text to TF-IDF features

# # Array representing the labels. Unlabeled samples should have the label -1.

review_data["recommend"] = review_data["recommend"].fillna(-1)


print("wow")
print(review_data[review_data["recommend"]==-1])


# for some reason the tyepe matter https://discuss.huggingface.co/t/valueerror-target-size-torch-size-8-must-be-the-same-as-input-size-torch-size-8-8/12133/9
train_df = pd.DataFrame({"text": review_data["review_comment"], "label": review_data["recommend"].astype(int)})



# Now we are working with huggingface daset 

train_dataset = Dataset.from_pandas(train_df)

print(sum(label == -1 for label in train_dataset["label"]))
print(train_dataset["label"])
unlabeled_mask =  train_dataset["label"] == -1
print(unlabeled_mask)
# Load tokenizer
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

# Bert model accepts max 512
# Tokenize datasets
def tokenize(batch):
    return tokenizer(batch["text"], truncation=True, padding='max_length', max_length=512)

#------------------------------------


#------------------------------------

# In Hugging Face models like BERT, the features come from the tokenized input data that is fed into the model.
# the map applie the tokenize function to each batch of the function 
train_dataset = train_dataset.map(tokenize, batched=True)

# print(train_dataset)
# Load model
# define model
model = BertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=2)


model, train_dataset = self_training_loop(model, train_dataset,tokenizer)

# Save the trained model and tokenizer
model.save_pretrained("self_trained_bert_model")
tokenizer.save_pretrained("self_trained_tokenizer")

# Save the final labeled dataset
train_dataset_df = train_dataset.to_pandas()  # Convert dataset back to pandas DataFrame
train_dataset_df = train_dataset_df[["label","text"]]
train_dataset_df.to_csv("final_labeled_reviews.csv", index=False)


#---------Evaluate-----------



train_dataset_df = train_dataset.to_pandas()  # Convert dataset back to pandas DataFrame
train_dataset_df = train_dataset_df[["label","text"]]
train_dataset_df.to_csv("final_labeled_reviews.csv", index=False)
review_data_test = pd.read_csv("/Users/apple/Documents/GitHub/Steam-Market-Data-ML/cleaned_reviews.csv",nrows=5000)



print(review_data_test ["review_comment"].isna().sum())
review_data_test ["review_comment"] = review_data_test ["review_comment"].fillna("") 
review_data_test ["recommend"] = review_data_test ["recommend"].map({"Recommended": 1, "Not Recommended": 0})
review_data_test ["recommend"] = review_data_test ["recommend"].fillna(-1)



review_y_test = review_data_test["recommend"]

train_dataset_frame =  train_dataset.to_pandas()
# only the unlabled data
mask = review_data["recommend"] == -1 
review_y_test =  review_y_test[mask]

final_data_set = train_dataset_frame[mask]
print(review_y_test)
print(final_data_set)

# print(review_X_train.shape[0])
# This metaestimator allows a given supervised classifier to function as a semi-supervised classifier, allowing it to learn from unlabeled data. 
# It does this by iteratively predicting pseudo-labels for the unlabeled data and adding them to the training set.

accuracy = accuracy_score(review_y_test, final_data_set["label"] )
precision = precision_score(review_y_test, final_data_set["label"]  ,average='macro')
recall = recall_score(review_y_test,final_data_set["label"]  ,average='macro')


print("\nEvaluation Results on Test Data:")
print(f"Accuracy:  {accuracy}")
print(f"Precision: {precision}")
print(f"Recall:    {recall}")

with open('evaluation_results_selftrain_noboot_bert_models.txt', 'w') as f:
    f.write(f"Accuracy after fine-tuning: {accuracy:.4f}\n")
    f.write(f"Precision: {precision:.4f}\n")
    f.write(f"Recall: {recall:.4f}\n")

Evlautation

Unlabeled prediction/unlableled data test on full data

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score
from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments
from sklearn.feature_extraction.text import TfidfVectorizer
from transformers import DataCollatorWithPadding
import torch
from datasets import Dataset
from trl import IterativeSFTTrainer
from tqdm import tqdm




# We are still in datafre

review_data = pd.read_csv("/Users/apple/Documents/GitHub/Steam-Market-Data-ML/unlabeled_reviews.csv")

print(review_data["review_comment"].isna().sum())
review_data["review_comment"] = review_data["review_comment"].fillna("") 
review_data["recommend"] = review_data["recommend"].map({"Recommended": 1, "Not Recommended": 0})



# vectorizer = TfidfVectorizer()

# review_X = vectorizer.fit_transform(review_data["review_comment"])  # Convert text to TF-IDF features

# # Array representing the labels. Unlabeled samples should have the label -1.

review_data["recommend"] = review_data["recommend"].fillna(-1)


# print("wow")
# print(review_data[review_data["recommend"]==-1])


# for some reason the tyepe matter https://discuss.huggingface.co/t/valueerror-target-size-torch-size-8-must-be-the-same-as-input-size-torch-size-8-8/12133/9
train_df = pd.DataFrame({"text": review_data["review_comment"], "label": review_data["recommend"].astype(int)})



# Now we are working with huggingface daset 

train_dataset = Dataset.from_pandas(train_df)

print(sum(label == -1 for label in train_dataset["label"]))
print(train_dataset["label"])
unlabeled_mask =  train_dataset["label"] == -1
# print(unlabeled_mask)
# Load tokenizer
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

# Bert model accepts max 512
# Tokenize datasets
def tokenize(batch):
    return tokenizer(batch["text"], truncation=True, padding='max_length', max_length=512)

#------------------------------------


#------------------------------------

# In Hugging Face models like BERT, the features come from the tokenized input data that is fed into the model.
# the map applie the tokenize function to each batch of the function 
train_dataset = train_dataset.map(tokenize, batched=True)

# print(train_dataset)
# Load model
# define model



# print (f"we are using {device}")

model = BertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=2)
device = torch.device("cpu")
model.to(device)


model, train_dataset = self_training_loop(model, train_dataset, threshold_mode = 'fix')

# Save the trained model and tokenizer
model.save_pretrained("self_trained_bert_final_model")
tokenizer.save_pretrained("self_trained_final_tokenizer")

# Save the final labeled dataset
train_dataset_df = train_dataset.to_pandas()  # Convert dataset back to pandas DataFrame
train_dataset_df = train_dataset_df[["label","text"]]
train_dataset_df.to_csv("final_labeled_reviews.csv", index=False)


#---------Evaluate-----------



train_dataset_df = train_dataset.to_pandas()  # Convert dataset back to pandas DataFrame
train_dataset_df = train_dataset_df[["label","text"]]
train_dataset_df.to_csv("final_labeled_reviews.csv", index=False)
review_data_test = pd.read_csv("/Users/apple/Documents/GitHub/Steam-Market-Data-ML/cleaned_reviews.csv")



print(review_data_test ["review_comment"].isna().sum())
review_data_test ["review_comment"] = review_data_test ["review_comment"].fillna("") 
review_data_test ["recommend"] = review_data_test ["recommend"].map({"Recommended": 1, "Not Recommended": 0})
review_data_test ["recommend"] = review_data_test ["recommend"].fillna(-1)



review_y_test = review_data_test["recommend"]

train_dataset_frame =  train_dataset.to_pandas()
# only the unlabled data
mask = review_data["recommend"] == -1 
review_y_test =  review_y_test[mask]

final_data_set = train_dataset_frame[mask]
# print(review_y_test)
# print(final_data_set)

# print(review_X_train.shape[0])
# This metaestimator allows a given supervised classifier to function as a semi-supervised classifier, allowing it to learn from unlabeled data. 
# It does this by iteratively predicting pseudo-labels for the unlabeled data and adding them to the training set.

accuracy = accuracy_score(review_y_test, final_data_set["label"] )
precision = precision_score(review_y_test, final_data_set["label"]  ,average='macro')
recall = recall_score(review_y_test,final_data_set["label"]  ,average='macro')


print("\nEvaluation Results on Test Data:")
print(f"Accuracy:  {accuracy}")
print(f"Precision: {precision}")
print(f"Recall:    {recall}")

with open('evaluation_results_selftrain_noboot_full_bert_models.txt', 'w') as f:
    f.write(f"Accuracy after fine-tuning: {accuracy:.4f}\n")
    f.write(f"Precision: {precision:.4f}\n")
    f.write(f"Recall: {recall:.4f}\n")

1
25056

Map:   0%|          | 0/83522 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Unlabeled Samples Remaining:   0%|          | 0/25056 [00:00<?, ?it/s]

Filter:   0%|          | 0/83522 [00:00<?, ? examples/s]

data:  labeled_train_dataset =Dataset({
    features: ['text', 'label', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 58466
})
0
hello

/opt/anaconda3/envs/cosc410_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py:685: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

Prediction Progress: 100%|██████████| 1306/1306 [13:55:47<00:00, 38.40s/it]

tensor([0.9092, 0.9805, 0.9984,  ..., 0.9939, 0.9360, 0.9959])
tensor([1, 1, 1,  ..., 1, 1, 1])
83522
------------------------

Map:   0%|          | 0/83522 [00:00<?, ? examples/s]

Unlabeled Samples Remaining:  84%|████████▍ | 21039/25056 [16:20:57<3:07:17,  2.80s/it]

Indices where the condition was met: [0, 9, 13, 17, 39, 42, 48, 52, 56, 59, 67, 68, 72, 74, 76, 78, 82, 90, 95, 96, 100, 104, 106, 107, 108, 115, 117, 119, 121, 125, 126, 127, 130, 138, 140, 143, 150, 153, 155, 158, 160, 161, 165, 166, 168, 174, 178, 183, 190, 196, 201, 204, 206, 212, 216, 217, 243, 244, 245, 246, 251, 257, 265, 270, 272, 273, 274, 276, 278, 279, 285, 286, 287, 288, 289, 292, 294, 300, 302, 307, 311, 315, 316, 317, 324, 325, 327, 329, 330, 345, 346, 350, 352, 354, 358, 362, 363, 367, 369, 378, 388, 391, 397, 398, 403, 408, 415, 417, 420, 425, 428, 433, 436, 437, 438, 439, 444, 446, 448, 449, 451, 457, 463, 467, 472, 475, 481, 482, 497, 499, 508, 521, 533, 535, 540, 543, 545, 546, 548, 549, 552, 554, 557, 558, 563, 566, 567, 568, 569, 583, 585, 588, 593, 594, 595, 600, 602, 611, 614, 615, 616, 617, 627, 628, 632, 633, 634, 640, 643, 644, 646, 648, 653, 656, 657, 661, 676, 677, 681, 687, 690, 692, 693, 695, 700, 701, 704, 705, 709, 712, 714, 718, 721, 723, 727, 732, 733, 735, 743, 751, 752, 753, 755, 757, 761, 762, 767, 770, 777, 780, 781, 787, 790, 793, 795, 798, 800, 803, 808, 818, 821, 823, 827, 833, 836, 838, 840, 844, 845, 847, 848, 851, 853, 855, 858, 861, 864, 865, 866, 868, 869, 871, 876, 878, 879, 884, 887, 889, 890, 892, 893, 896, 900, 906, 907, 914, 917, 919, 922, 929, 930, 942, 949, 950, 960, 968, 979, 984, 986, 997, 1006, 1007, 1008, 1011, 1013, 1015, 1016, 1019, 1023, 1026, 1028, 1034, 1035, 1037, 1038, 1039, 1041, 1048, 1049, 1051, 1057, 1058, 1065, 1068, 1069, 1073, 1076, 1086, 1088, 1089, 1092, 1093, 1094, 1095, 1097, 1098, 1099, 1102, 1105, 1108, 1111, 1112, 1114, 1118, 1121, 1124, 1127, 1131, 1134, 1136, 1143, 1147, 1153, 1154, 1155, 1163, 1164, 1166, 1174, 1188, 1190, 1192, 1196, 1198, 1199, 1205, 1207, 1209, 1211, 1214, 1216, 1219, 1221, 1224, 1225, 1229, 1238, 1241, 1242, 1254, 1256, 1257, 1262, 1264, 1271, 1274, 1275, 1277, 1281, 1283, 1289, 1294, 1296, 1298, 1300, 1304, 1310, 1319, 1322, 1323, 1325, 1327, 1334, 1335, 1336, 1338, 1339, 1340, 1342, 1344, 1350, 1354, 1365, 1366, 1370, 1372, 1377, 1380, 1382, 1383, 1384, 1387, 1388, 1390, 1395, 1396, 1397, 1400, 1401, 1404, 1406, 1413, 1415, 1417, 1419, 1420, 1437, 1438, 1439, 1444, 1446, 1448, 1460, 1462, 1464, 1465, 1469, 1473, 1481, 1494, 1499, 1502, 1505, 1508, 1509, 1516, 1519, 1520, 1521, 1522, 1529, 1532, 1533, 1538, 1540, 1543, 1547, 1549, 1552, 1555, 1556, 1560, 1563, 1572, 1575, 1590, 1594, 1601, 1603, 1605, 1617, 1622, 1625, 1635, 1639, 1644, 1656, 1659, 1663, 1667, 1676, 1678, 1679, 1683, 1690, 1693, 1694, 1695, 1696, 1702, 1703, 1704, 1719, 1723, 1724, 1725, 1727, 1735, 1736, 1743, 1745, 1748, 1761, 1770, 1772, 1773, 1780, 1785, 1792, 1795, 1801, 1803, 1807, 1808, 1809, 1812, 1815, 1818, 1821, 1822, 1823, 1829, 1830, 1831, 1833, 1836, 1837, 1844, 1848, 1849, 1852, 1854, 1855, 1858, 1859, 1861, 1863, 1871, 1872, 1878, 1880, 1884, 1887, 1888, 1895, 1903, 1907, 1914, 1916, 1923, 1925, 1926, 1928, 1929, 1933, 1935, 1938, 1939, 1946, 1953, 1954, 1955, 1956, 1957, 1959, 1967, 1971, 1974, 1978, 1980, 1982, 1985, 1986, 1988, 1991, 1994, 1996, 1999, 2002, 2004, 2014, 2015, 2016, 2018, 2022, 2027, 2029, 2032, 2034, 2037, 2038, 2039, 2040, 2042, 2047, 2049, 2054, 2055, 2056, 2057, 2063, 2073, 2075, 2078, 2081, 2082, 2087, 2089, 2094, 2096, 2101, 2102, 2112, 2116, 2120, 2123, 2125, 2134, 2135, 2138, 2145, 2147, 2152, 2154, 2156, 2159, 2162, 2167, 2170, 2173, 2179, 2183, 2189, 2198, 2206, 2207, 2208, 2209, 2212, 2220, 2225, 2228, 2229, 2232, 2248, 2250, 2251, 2255, 2256, 2260, 2273, 2279, 2287, 2295, 2298, 2299, 2315, 2317, 2321, 2323, 2326, 2327, 2330, 2331, 2335, 2336, 2337, 2338, 2357, 2361, 2366, 2370, 2372, 2374, 2376, 2378, 2381, 2382, 2383, 2390, 2396, 2401, 2404, 2406, 2407, 2412, 2417, 2422, 2426, 2427, 2430, 2435, 2436, 2438, 2440, 2442, 2447, 2448, 2451, 2454, 2459, 2461, 2464, 2465, 2466, 2468, 2481, 2484, 2485, 2488, 2502, 2504, 2505, 2509, 2513, 2514, 2516, 2522, 2527, 2530, 2531, 2534, 2536, 2537, 2538, 2539, 2543, 2544, 2546, 2547, 2548, 2550, 2551, 2556, 2565, 2569, 2570, 2572, 2574, 2576, 2586, 2587, 2593, 2595, 2596, 2597, 2599, 2602, 2607, 2608, 2610, 2611, 2613, 2614, 2619, 2620, 2626, 2633, 2637, 2638, 2639, 2642, 2644, 2649, 2652, 2653, 2654, 2655, 2656, 2667, 2668, 2674, 2681, 2682, 2689, 2691, 2692, 2693, 2697, 2698, 2700, 2704, 2706, 2718, 2719, 2725, 2739, 2741, 2744, 2745, 2747, 2755, 2756, 2757, 2759, 2761, 2774, 2775, 2785, 2788, 2796, 2799, 2803, 2804, 2806, 2815, 2818, 2819, 2821, 2823, 2829, 2833, 2834, 2836, 2837, 2839, 2841, 2861, 2863, 2868, 2873, 2877, 2884, 2885, 2890, 2893, 2894, 2897, 2898, 2906, 2908, 2910, 2913, 2920, 2927, 2932, 2934, 2936, 2938, 2940, 2944, 2945, 2951, 2955, 2958, 2959, 2961, 2963, 2964, 2966, 2967, 2969, 2985, 2993, 2997, 3003, 3006, 3013, 3023, 3025, 3026, 3030, 3031, 3037, 3042, 3045, 3047, 3048, 3050, 3054, 3059, 3062, 3075, 3077, 3079, 3081, 3085, 3088, 3092, 3098, 3102, 3105, 3106, 3109, 3115, 3117, 3120, 3122, 3136, 3138, 3140, 3146, 3152, 3155, 3157, 3158, 3159, 3162, 3164, 3170, 3175, 3178, 3181, 3184, 3186, 3188, 3198, 3200, 3204, 3205, 3212, 3215, 3219, 3230, 3232, 3234, 3235, 3237, 3239, 3241, 3252, 3255, 3259, 3261, 3262, 3264, 3265, 3266, 3268, 3276, 3281, 3282, 3285, 3291, 3292, 3296, 3297, 3301, 3305, 3307, 3309, 3321, 3322, 3327, 3332, 3335, 3337, 3339, 3341, 3344, 3345, 3348, 3350, 3351, 3353, 3356, 3359, 3363, 3374, 3376, 3378, 3379, 3380, 3385, 3386, 3387, 3394, 3395, 3399, 3400, 3402, 3405, 3409, 3418, 3428, 3433, 3439, 3441, 3444, 3451, 3458, 3460, 3463, 3464, 3467, 3471, 3473, 3476, 3485, 3492, 3498, 3499, 3500, 3502, 3504, 3509, 3510, 3511, 3512, 3522, 3534, 3535, 3539, 3542, 3544, 3551, 3553, 3554, 3560, 3562, 3566, 3567, 3568, 3574, 3575, 3577, 3583, 3586, 3587, 3592, 3595, 3598, 3600, 3603, 3608, 3610, 3618, 3628, 3636, 3637, 3640, 3648, 3654, 3656, 3658, 3659, 3661, 3668, 3672, 3673, 3675, 3676, 3682, 3688, 3690, 3694, 3695, 3698, 3703, 3709, 3710, 3713, 3715, 3720, 3723, 3724, 3728, 3730, 3741, 3746, 3748, 3749, 3752, 3754, 3755, 3757, 3758, 3762, 3763, 3769, 3776, 3778, 3783, 3786, 3787, 3788, 3789, 3794, 3795, 3807, 3813, 3814, 3816, 3822, 3823, 3824, 3825, 3829, 3830, 3835, 3838, 3839, 3848, 3851, 3853, 3860, 3863, 3865, 3869, 3873, 3878, 3880, 3882, 3884, 3888, 3889, 3892, 3893, 3902, 3904, 3908, 3909, 3915, 3922, 3925, 3930, 3933, 3934, 3935, 3936, 3940, 3942, 3943, 3945, 3949, 3953, 3959, 3961, 3964, 3967, 3970, 3972, 3973, 3989, 3994, 3995, 3999, 4000, 4002, 4009, 4013, 4017, 4018, 4025, 4027, 4032, 4042, 4054, 4055, 4057, 4077, 4079, 4086, 4089, 4102, 4108, 4109, 4117, 4122, 4131, 4135, 4146, 4149, 4153, 4154, 4155, 4160, 4161, 4168, 4169, 4170, 4177, 4187, 4194, 4195, 4197, 4203, 4206, 4209, 4212, 4215, 4218, 4223, 4235, 4239, 4243, 4246, 4248, 4252, 4255, 4256, 4258, 4259, 4267, 4270, 4273, 4277, 4284, 4286, 4287, 4289, 4303, 4308, 4310, 4311, 4322, 4326, 4330, 4331, 4333, 4336, 4344, 4347, 4349, 4357, 4358, 4365, 4366, 4369, 4375, 4376, 4382, 4383, 4389, 4392, 4395, 4397, 4398, 4399, 4403, 4405, 4409, 4416, 4418, 4419, 4422, 4423, 4424, 4426, 4429, 4430, 4441, 4442, 4448, 4449, 4452, 4459, 4460, 4463, 4467, 4468, 4476, 4479, 4481, 4484, 4486, 4487, 4493, 4496, 4506, 4508, 4513, 4514, 4518, 4519, 4520, 4523, 4527, 4533, 4542, 4550, 4564, 4576, 4581, 4590, 4594, 4598, 4599, 4603, 4606, 4610, 4612, 4616, 4617, 4620, 4623, 4624, 4631, 4634, 4640, 4643, 4645, 4646, 4649, 4658, 4659, 4661, 4676, 4684, 4687, 4697, 4700, 4701, 4703, 4710, 4711, 4714, 4724, 4728, 4729, 4737, 4742, 4745, 4746, 4750, 4756, 4759, 4764, 4766, 4768, 4779, 4785, 4793, 4798, 4801, 4807, 4809, 4812, 4814, 4816, 4817, 4824, 4827, 4828, 4830, 4837, 4842, 4843, 4852, 4856, 4857, 4866, 4875, 4876, 4883, 4884, 4893, 4896, 4901, 4911, 4912, 4917, 4920, 4923, 4932, 4942, 4959, 4960, 4963, 4964, 4973, 4990, 4998, 4999, 5003, 5011, 5015, 5017, 5020, 5036, 5037, 5038, 5039, 5045, 5050, 5052, 5062, 5063, 5065, 5070, 5072, 5075, 5081, 5085, 5100, 5104, 5112, 5114, 5117, 5121, 5141, 5146, 5154, 5163, 5164, 5166, 5169, 5176, 5177, 5180, 5183, 5185, 5189, 5210, 5212, 5214, 5216, 5217, 5218, 5223, 5227, 5231, 5234, 5240, 5241, 5248, 5255, 5259, 5271, 5273, 5275, 5279, 5286, 5287, 5290, 5293, 5294, 5295, 5299, 5303, 5307, 5310, 5311, 5312, 5330, 5334, 5335, 5336, 5337, 5352, 5354, 5356, 5361, 5366, 5370, 5372, 5378, 5384, 5385, 5387, 5388, 5391, 5393, 5396, 5397, 5402, 5406, 5411, 5417, 5426, 5432, 5435, 5436, 5440, 5446, 5456, 5458, 5459, 5461, 5464, 5467, 5468, 5476, 5478, 5482, 5487, 5489, 5491, 5492, 5495, 5496, 5499, 5500, 5501, 5503, 5508, 5513, 5522, 5525, 5528, 5530, 5536, 5545, 5546, 5552, 5555, 5562, 5564, 5565, 5571, 5572, 5573, 5574, 5577, 5580, 5584, 5588, 5589, 5593, 5597, 5602, 5604, 5611, 5613, 5616, 5619, 5625, 5630, 5632, 5634, 5635, 5638, 5640, 5650, 5653, 5654, 5662, 5663, 5664, 5669, 5670, 5671, 5673, 5675, 5679, 5680, 5681, 5682, 5684, 5687, 5715, 5716, 5718, 5719, 5722, 5723, 5725, 5728, 5733, 5737, 5738, 5742, 5745, 5746, 5747, 5749, 5751, 5752, 5753, 5759, 5765, 5768, 5769, 5772, 5773, 5779, 5781, 5783, 5793, 5796, 5799, 5806, 5811, 5815, 5820, 5824, 5825, 5829, 5830, 5834, 5837, 5844, 5846, 5847, 5849, 5850, 5851, 5852, 5853, 5857, 5863, 5864, 5870, 5871, 5873, 5874, 5875, 5882, 5884, 5885, 5889, 5892, 5894, 5895, 5905, 5906, 5907, 5914, 5915, 5919, 5927, 5934, 5936, 5937, 5938, 5939, 5944, 5946, 5948, 5961, 5962, 5973, 5976, 5977, 5978, 5989, 5990, 5991, 5999, 6008, 6013, 6015, 6020, 6022, 6023, 6025, 6027, 6033, 6036, 6038, 6039, 6043, 6044, 6045, 6046, 6047, 6054, 6055, 6056, 6063, 6065, 6068, 6069, 6075, 6076, 6079, 6080, 6081, 6085, 6086, 6095, 6098, 6099, 6100, 6107, 6110, 6115, 6117, 6124, 6126, 6127, 6128, 6131, 6135, 6138, 6144, 6148, 6151, 6155, 6156, 6163, 6164, 6168, 6169, 6172, 6175, 6186, 6187, 6188, 6194, 6200, 6204, 6205, 6210, 6211, 6212, 6214, 6215, 6218, 6219, 6220, 6221, 6227, 6231, 6245, 6249, 6251, 6253, 6259, 6260, 6266, 6269, 6272, 6279, 6281, 6282, 6286, 6288, 6290, 6298, 6308, 6311, 6317, 6319, 6320, 6329, 6331, 6339, 6340, 6346, 6351, 6352, 6357, 6363, 6366, 6375, 6385, 6387, 6390, 6392, 6394, 6401, 6404, 6409, 6416, 6420, 6422, 6423, 6433, 6434, 6435, 6437, 6438, 6440, 6452, 6453, 6457, 6459, 6464, 6466, 6475, 6476, 6482, 6483, 6490, 6493, 6498, 6503, 6504, 6505, 6507, 6508, 6510, 6519, 6521, 6523, 6527, 6551, 6552, 6564, 6567, 6574, 6587, 6590, 6591, 6595, 6597, 6598, 6604, 6607, 6608, 6609, 6612, 6618, 6621, 6622, 6626, 6628, 6629, 6633, 6636, 6638, 6639, 6648, 6653, 6655, 6661, 6662, 6668, 6675, 6677, 6689, 6693, 6702, 6713, 6715, 6723, 6726, 6727, 6733, 6735, 6740, 6742, 6744, 6747, 6749, 6750, 6752, 6753, 6756, 6764, 6767, 6773, 6777, 6778, 6788, 6793, 6795, 6799, 6801, 6810, 6819, 6823, 6826, 6829, 6843, 6850, 6851, 6857, 6861, 6863, 6864, 6876, 6877, 6880, 6888, 6889, 6896, 6900, 6901, 6908, 6911, 6913, 6914, 6922, 6934, 6937, 6945, 6947, 6958, 6960, 6964, 6965, 6969, 6973, 6974, 6975, 6983, 6984, 6988, 6996, 6998, 7002, 7005, 7006, 7016, 7020, 7022, 7024, 7031, 7032, 7036, 7039, 7044, 7045, 7048, 7050, 7052, 7065, 7067, 7073, 7077, 7083, 7085, 7087, 7089, 7093, 7096, 7103, 7105, 7106, 7107, 7110, 7112, 7119, 7123, 7124, 7128, 7132, 7134, 7141, 7143, 7145, 7153, 7157, 7158, 7183, 7194, 7197, 7203, 7204, 7206, 7209, 7214, 7215, 7217, 7218, 7220, 7223, 7225, 7229, 7233, 7239, 7250, 7254, 7260, 7267, 7268, 7275, 7276, 7280, 7283, 7303, 7305, 7307, 7317, 7318, 7330, 7335, 7338, 7341, 7344, 7350, 7351, 7358, 7359, 7360, 7361, 7362, 7364, 7368, 7371, 7376, 7377, 7378, 7379, 7380, 7383, 7384, 7385, 7386, 7387, 7389, 7390, 7392, 7393, 7394, 7400, 7404, 7411, 7417, 7418, 7425, 7429, 7434, 7438, 7440, 7442, 7448, 7452, 7453, 7454, 7456, 7459, 7460, 7462, 7466, 7467, 7469, 7471, 7473, 7474, 7475, 7483, 7492, 7494, 7495, 7496, 7499, 7501, 7504, 7509, 7511, 7513, 7517, 7518, 7528, 7529, 7530, 7531, 7532, 7535, 7544, 7547, 7548, 7552, 7553, 7558, 7562, 7568, 7571, 7573, 7574, 7576, 7582, 7594, 7599, 7602, 7604, 7610, 7612, 7613, 7615, 7619, 7629, 7630, 7633, 7642, 7646, 7650, 7661, 7663, 7665, 7667, 7675, 7678, 7679, 7682, 7683, 7687, 7691, 7696, 7698, 7699, 7701, 7703, 7704, 7705, 7707, 7709, 7716, 7730, 7732, 7734, 7735, 7742, 7744, 7746, 7751, 7752, 7753, 7754, 7755, 7756, 7758, 7765, 7767, 7770, 7775, 7777, 7779, 7784, 7788, 7789, 7794, 7800, 7801, 7802, 7804, 7805, 7808, 7812, 7817, 7821, 7823, 7824, 7826, 7830, 7831, 7835, 7838, 7839, 7843, 7845, 7850, 7853, 7856, 7860, 7861, 7863, 7866, 7869, 7877, 7884, 7886, 7889, 7897, 7899, 7900, 7901, 7907, 7908, 7911, 7919, 7922, 7924, 7925, 7928, 7934, 7935, 7944, 7945, 7952, 7958, 7960, 7963, 7968, 7980, 7984, 7988, 7990, 7998, 7999, 8001, 8003, 8007, 8009, 8018, 8022, 8026, 8028, 8037, 8040, 8041, 8046, 8047, 8050, 8051, 8054, 8059, 8062, 8067, 8076, 8086, 8088, 8099, 8105, 8108, 8115, 8118, 8121, 8122, 8127, 8128, 8129, 8130, 8131, 8132, 8133, 8140, 8146, 8152, 8153, 8155, 8157, 8158, 8160, 8172, 8179, 8184, 8185, 8187, 8196, 8199, 8200, 8203, 8205, 8208, 8215, 8225, 8227, 8236, 8237, 8239, 8240, 8241, 8247, 8248, 8252, 8254, 8256, 8257, 8261, 8264, 8265, 8266, 8267, 8268, 8272, 8276, 8284, 8288, 8292, 8293, 8296, 8298, 8302, 8316, 8319, 8321, 8328, 8330, 8332, 8334, 8341, 8348, 8356, 8365, 8367, 8370, 8374, 8376, 8377, 8378, 8387, 8388, 8390, 8394, 8397, 8401, 8402, 8405, 8406, 8407, 8411, 8419, 8420, 8423, 8424, 8427, 8428, 8430, 8432, 8436, 8439, 8440, 8441, 8447, 8448, 8449, 8454, 8455, 8460, 8461, 8464, 8467, 8468, 8470, 8475, 8479, 8483, 8486, 8487, 8488, 8490, 8495, 8497, 8498, 8501, 8512, 8520, 8521, 8530, 8533, 8545, 8549, 8554, 8561, 8562, 8564, 8565, 8567, 8572, 8576, 8581, 8582, 8584, 8585, 8589, 8593, 8598, 8604, 8606, 8607, 8610, 8611, 8612, 8620, 8622, 8627, 8630, 8633, 8636, 8637, 8640, 8641, 8654, 8662, 8665, 8669, 8675, 8677, 8682, 8683, 8690, 8691, 8694, 8697, 8698, 8713, 8714, 8715, 8718, 8736, 8739, 8740, 8743, 8744, 8745, 8747, 8749, 8752, 8753, 8754, 8755, 8760, 8763, 8766, 8767, 8769, 8782, 8786, 8791, 8793, 8795, 8797, 8799, 8808, 8812, 8815, 8819, 8822, 8825, 8834, 8835, 8840, 8841, 8853, 8857, 8858, 8861, 8864, 8878, 8885, 8886, 8887, 8894, 8897, 8899, 8916, 8920, 8923, 8936, 8945, 8947, 8949, 8958, 8965, 8970, 8972, 8973, 8982, 8983, 8984, 8985, 8989, 9000, 9003, 9006, 9007, 9014, 9021, 9024, 9025, 9026, 9033, 9034, 9035, 9038, 9039, 9041, 9055, 9061, 9066, 9067, 9070, 9072, 9073, 9074, 9075, 9077, 9079, 9083, 9086, 9087, 9096, 9098, 9103, 9107, 9117, 9118, 9120, 9125, 9127, 9142, 9143, 9145, 9147, 9152, 9155, 9158, 9167, 9169, 9170, 9171, 9174, 9175, 9178, 9182, 9184, 9186, 9196, 9197, 9198, 9199, 9215, 9220, 9224, 9228, 9229, 9230, 9236, 9238, 9246, 9251, 9254, 9262, 9264, 9267, 9269, 9271, 9272, 9273, 9275, 9276, 9287, 9288, 9289, 9290, 9293, 9298, 9301, 9308, 9313, 9314, 9323, 9326, 9328, 9329, 9331, 9334, 9336, 9338, 9347, 9352, 9356, 9358, 9362, 9365, 9366, 9370, 9379, 9386, 9391, 9394, 9395, 9397, 9401, 9404, 9406, 9409, 9411, 9416, 9420, 9421, 9427, 9432, 9435, 9436, 9439, 9441, 9442, 9454, 9455, 9456, 9471, 9478, 9479, 9482, 9487, 9495, 9497, 9501, 9502, 9503, 9510, 9513, 9514, 9521, 9522, 9523, 9525, 9527, 9531, 9534, 9538, 9540, 9545, 9550, 9556, 9561, 9568, 9569, 9570, 9576, 9577, 9581, 9584, 9592, 9595, 9597, 9598, 9600, 9602, 9603, 9605, 9607, 9610, 9612, 9613, 9616, 9618, 9622, 9637, 9643, 9646, 9650, 9651, 9655, 9656, 9662, 9663, 9665, 9666, 9672, 9676, 9678, 9685, 9687, 9690, 9692, 9695, 9705, 9708, 9710, 9712, 9713, 9715, 9716, 9717, 9721, 9730, 9732, 9735, 9738, 9740, 9743, 9745, 9752, 9754, 9758, 9759, 9760, 9772, 9776, 9781, 9794, 9796, 9799, 9802, 9805, 9809, 9812, 9813, 9820, 9829, 9835, 9836, 9839, 9842, 9843, 9846, 9853, 9857, 9860, 9865, 9870, 9872, 9873, 9876, 9877, 9879, 9882, 9883, 9886, 9890, 9893, 9895, 9896, 9899, 9905, 9907, 9909, 9917, 9919, 9920, 9928, 9931, 9936, 9939, 9947, 9948, 9949, 9951, 9952, 9955, 9965, 9966, 9969, 9972, 9976, 9983, 9986, 9988, 9992, 10015, 10016, 10026, 10030, 10031, 10033, 10036, 10041, 10048, 10049, 10055, 10059, 10066, 10069, 10074, 10076, 10077, 10078, 10079, 10081, 10085, 10093, 10099, 10106, 10110, 10111, 10124, 10130, 10135, 10136, 10144, 10145, 10149, 10150, 10157, 10159, 10161, 10166, 10167, 10168, 10171, 10176, 10177, 10188, 10189, 10190, 10192, 10193, 10195, 10200, 10203, 10204, 10208, 10210, 10219, 10227, 10228, 10233, 10237, 10241, 10242, 10244, 10250, 10255, 10260, 10261, 10267, 10268, 10269, 10270, 10278, 10279, 10280, 10282, 10287, 10288, 10294, 10296, 10303, 10304, 10307, 10309, 10315, 10316, 10318, 10321, 10322, 10324, 10326, 10327, 10330, 10338, 10339, 10344, 10345, 10347, 10348, 10349, 10350, 10351, 10355, 10357, 10358, 10361, 10371, 10374, 10381, 10383, 10386, 10390, 10392, 10393, 10403, 10405, 10406, 10407, 10409, 10411, 10418, 10422, 10425, 10430, 10438, 10439, 10443, 10453, 10456, 10464, 10468, 10469, 10471, 10472, 10475, 10477, 10486, 10490, 10491, 10499, 10503, 10505, 10506, 10513, 10515, 10517, 10522, 10523, 10526, 10528, 10533, 10536, 10542, 10547, 10557, 10558, 10562, 10566, 10569, 10571, 10572, 10576, 10578, 10582, 10584, 10587, 10588, 10590, 10591, 10593, 10596, 10599, 10600, 10605, 10612, 10616, 10619, 10620, 10626, 10631, 10634, 10642, 10643, 10645, 10647, 10653, 10657, 10662, 10663, 10664, 10667, 10668, 10669, 10671, 10676, 10677, 10680, 10690, 10691, 10695, 10698, 10701, 10704, 10708, 10712, 10717, 10725, 10726, 10729, 10733, 10734, 10735, 10737, 10738, 10739, 10745, 10747, 10749, 10752, 10753, 10755, 10759, 10761, 10769, 10773, 10776, 10779, 10780, 10783, 10785, 10789, 10790, 10795, 10800, 10806, 10810, 10812, 10817, 10827, 10828, 10829, 10832, 10836, 10839, 10840, 10845, 10846, 10847, 10849, 10854, 10855, 10856, 10862, 10867, 10871, 10873, 10875, 10882, 10889, 10894, 10895, 10896, 10905, 10908, 10912, 10913, 10915, 10916, 10927, 10933, 10941, 10942, 10945, 10946, 10951, 10954, 10956, 10960, 10966, 10967, 10969, 10972, 10974, 10975, 10978, 10979, 10983, 10987, 10988, 10990, 10995, 11004, 11005, 11007, 11009, 11010, 11012, 11013, 11014, 11020, 11023, 11024, 11028, 11030, 11032, 11043, 11057, 11061, 11065, 11068, 11070, 11087, 11092, 11093, 11098, 11101, 11105, 11111, 11116, 11122, 11141, 11145, 11148, 11151, 11156, 11157, 11159, 11160, 11164, 11166, 11171, 11175, 11176, 11177, 11178, 11180, 11185, 11188, 11189, 11190, 11205, 11207, 11210, 11211, 11214, 11223, 11227, 11230, 11237, 11245, 11249, 11253, 11257, 11258, 11261, 11267, 11268, 11273, 11287, 11288, 11289, 11299, 11301, 11306, 11307, 11312, 11315, 11317, 11320, 11326, 11328, 11332, 11334, 11340, 11341, 11342, 11348, 11350, 11358, 11361, 11364, 11365, 11366, 11369, 11370, 11375, 11381, 11387, 11390, 11391, 11392, 11393, 11396, 11397, 11398, 11400, 11401, 11407, 11409, 11416, 11421, 11422, 11423, 11438, 11441, 11443, 11447, 11467, 11471, 11478, 11488, 11496, 11501, 11503, 11506, 11514, 11516, 11519, 11522, 11526, 11536, 11539, 11541, 11546, 11557, 11559, 11570, 11573, 11575, 11576, 11581, 11584, 11585, 11588, 11592, 11599, 11600, 11615, 11617, 11620, 11628, 11629, 11631, 11641, 11643, 11645, 11647, 11655, 11659, 11660, 11663, 11667, 11671, 11674, 11679, 11680, 11682, 11684, 11686, 11687, 11689, 11692, 11695, 11696, 11699, 11705, 11706, 11707, 11718, 11724, 11726, 11731, 11734, 11735, 11740, 11745, 11746, 11751, 11755, 11760, 11762, 11764, 11765, 11771, 11773, 11778, 11779, 11793, 11796, 11797, 11800, 11803, 11825, 11839, 11844, 11853, 11855, 11860, 11863, 11868, 11875, 11876, 11877, 11880, 11882, 11886, 11894, 11898, 11900, 11901, 11905, 11909, 11911, 11912, 11913, 11915, 11928, 11931, 11934, 11937, 11938, 11941, 11950, 11954, 11955, 11958, 11968, 11973, 11977, 11983, 11988, 11991, 11992, 11998, 12001, 12003, 12013, 12015, 12018, 12023, 12025, 12031, 12051, 12055, 12061, 12066, 12071, 12073, 12074, 12083, 12084, 12093, 12096, 12098, 12099, 12106, 12112, 12113, 12114, 12120, 12121, 12123, 12127, 12128, 12140, 12145, 12146, 12148, 12151, 12158, 12159, 12167, 12168, 12171, 12172, 12173, 12177, 12182, 12184, 12189, 12193, 12194, 12197, 12200, 12201, 12204, 12207, 12211, 12215, 12220, 12228, 12237, 12238, 12240, 

/opt/anaconda3/envs/cosc410_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py:685: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

Prediction Progress: 100%|██████████| 1306/1306 [14:43:24<00:00, 40.59s/it]

tensor([0.9978, 0.9966, 0.9987,  ..., 0.9952, 0.9921, 0.9985])
tensor([1, 1, 1,  ..., 1, 1, 1])
83522
------------------------

Map:   0%|          | 0/83522 [00:00<?, ? examples/s]

Unlabeled Samples Remaining:  96%|█████████▌| 23981/25056 [34:52:46<1:49:25,  6.11s/it]

Indices where the condition was met: [18, 26, 54, 80, 88, 110, 208, 214, 271, 295, 310, 340, 374, 474, 520, 524, 584, 606, 607, 629, 667, 696, 703, 744, 901, 934, 970, 1120, 1156, 1162, 1171, 1227, 1235, 1288, 1303, 1305, 1347, 1361, 1443, 1466, 1645, 1729, 1758, 1898, 1901, 1922, 2077, 2110, 2137, 2174, 2352, 2385, 2402, 2508, 2618, 2647, 2699, 2791, 2824, 2828, 2831, 2844, 2970, 3004, 3022, 3116, 3195, 3233, 3270, 3278, 3300, 3354, 3358, 3403, 3407, 3443, 3513, 3523, 3576, 3667, 3683, 3696, 3734, 3767, 3910, 3916, 3938, 3975, 4021, 4058, 4110, 4240, 4245, 4253, 4260, 4341, 4454, 4559, 4562, 4601, 4618, 4662, 4685, 4767, 4850, 4865, 4873, 4889, 4894, 4906, 4915, 4927, 4929, 4934, 4953, 4967, 4981, 4984, 5018, 5030, 5041, 5049, 5057, 5078, 5090, 5091, 5110, 5115, 5136, 5148, 5150, 5153, 5162, 5184, 5187, 5239, 5364, 5368, 5420, 5423, 5463, 5553, 5622, 5627, 5657, 5706, 5888, 5899, 5912, 5949, 6067, 6111, 6190, 6229, 6234, 6318, 6481, 6525, 6530, 6561, 6562, 6596, 6611, 6637, 6663, 6664, 6673, 6674, 6679, 6695, 6712, 6805, 6839, 6858, 6894, 6912, 6919, 6920, 6941, 6962, 6987, 7062, 7100, 7202, 7226, 7255, 7306, 7312, 7320, 7486, 7493, 7519, 7539, 7546, 7555, 7603, 7635, 7708, 7731, 7833, 7871, 7895, 7904, 7918, 8211, 8234, 8263, 8304, 8350, 8364, 8446, 8508, 8553, 8568, 8594, 8651, 8693, 8734, 8953, 8997, 9116, 9162, 9430, 9625, 9629, 9767, 9788, 9855, 9864, 9916, 10012, 10018, 10182, 10482, 10493, 10568, 10607, 10682, 10886, 10893, 10958, 10961, 10997, 11037, 11049, 11090, 11096, 11133, 11183, 11212, 11254, 11331, 11427, 11479, 11491, 11640, 11665, 11703, 11759, 11763, 11834, 11893, 11989, 12005, 12006, 12019, 12029, 12041, 12126, 12216, 12234, 12239, 12243, 12281, 12298, 12310, 12357, 12380, 12385, 12390, 12426, 12428, 12446, 12544, 12551, 12622, 12629, 12632, 12659, 12685, 12718, 12752, 12812, 12814, 12837, 12841, 12843, 12858, 12922, 12938, 12997, 13073, 13085, 13138, 13158, 13280, 13296, 13307, 13325, 13478, 13481, 13485, 13496, 13512, 13536, 13551, 13572, 13607, 13622, 13691, 13692, 13804, 13807, 13829, 13867, 13869, 13891, 13980, 13981, 13997, 14157, 14219, 14224, 14368, 14376, 14394, 14397, 14432, 14448, 14532, 14542, 14560, 14657, 14677, 14708, 14710, 14748, 14749, 14762, 14775, 14802, 14817, 14843, 14845, 14925, 14971, 14990, 14995, 14999, 15033, 15041, 15044, 15052, 15060, 15071, 15092, 15104, 15105, 15109, 15113, 15119, 15149, 15153, 15220, 15244, 15245, 15327, 15336, 15408, 15429, 15575, 15681, 15728, 15766, 15873, 15921, 15926, 16045, 16145, 16191, 16213, 16250, 16306, 16347, 16461, 16513, 16527, 16533, 16556, 16576, 16582, 16609, 16622, 16655, 16656, 16721, 16754, 16770, 16784, 16789, 16957, 16987, 16988, 17222, 17271, 17357, 17418, 17449, 17523, 17577, 17677, 17680, 17702, 17768, 17786, 17874, 17895, 17899, 17989, 18018, 18022, 18104, 18181, 18303, 18311, 18360, 18378, 18400, 18467, 18478, 18537, 18547, 18560, 18649, 18669, 18678, 18767, 18772, 18779, 18786, 18799, 18808, 18845, 18847, 18852, 18920, 18927, 18943, 18962, 18972, 18982, 18999, 19018, 19019, 19063, 19072, 19094, 19102, 19105, 19107, 19119, 19121, 19288, 19365, 19425, 19516, 19559, 19594, 19600, 19789, 19911, 19972, 20099, 20112, 20219, 20286, 20291, 20426, 20458, 20459, 20461, 20550, 20662, 20837, 20902, 20946, 20960, 21031, 21049, 21050, 21055, 21067, 21122, 21219, 21235, 21263, 21267, 21295, 21432, 21524, 21554, 21559, 21659, 21666, 21771, 21820, 21943, 21946, 22013, 22031, 22061, 22067, 22069, 22079, 22094, 22117, 22131, 22149, 22199, 22204, 22218, 22269, 22312, 22321, 22328, 22344, 22345, 22369, 22398, 22419, 22436, 22468, 22477, 22483, 22584, 22637, 22750, 22762, 22785, 22791, 22792, 22800, 22840, 22842, 22915, 22923, 22937, 22989, 22990, 23006, 23031, 23032, 23039, 23050, 23071, 23098, 23131, 23192, 23193, 23262, 23268, 23333, 23371, 23398, 23418, 23441, 23514, 23519, 23555, 23569, 23587, 23630, 23641, 23721, 23761, 23773, 23787, 23789, 23816, 23920, 23923, 23932, 23935, 23996, 23997, 24027, 24048, 24113, 24214, 24225, 24229, 24279, 24287, 24374, 24404, 24437, 24592, 24605, 24725, 24736, 24744, 24766, 24768, 24785, 24795, 24851, 24872, 24955, 24963, 25066, 25211, 25264, 25291, 25321, 25378, 25393, 25478, 25538, 25570, 25700, 25707, 25715, 25718, 25726, 25793, 25843, 25922, 26001, 26011, 26170, 26198, 26330, 26347, 26389, 26470, 26532, 26548, 26605, 26670, 26703, 26772, 26780, 26810, 26872, 26885, 26958, 27008, 27016, 27036, 27053, 27067, 27070, 27071, 27081, 27099, 27188, 27226, 27228, 27229, 27250, 27262, 27272, 27323, 27334, 27357, 27382, 27386, 27442, 27443, 27480, 27578, 27593, 27608, 27618, 27664, 27689, 27820, 27827, 27830, 27831, 27852, 27862, 27890, 27917, 27954, 27957, 27964, 28059, 28097, 28166, 28226, 28238, 28259, 28271, 28323, 28361, 28485, 28564, 28686, 28700, 28717, 28840, 28860, 28899, 28919, 28979, 29019, 29077, 29090, 29128, 29197, 29215, 29231, 29251, 29269, 29313, 29335, 29351, 29363, 29365, 29384, 29394, 29430, 29463, 29484, 29523, 29549, 29603, 29633, 29654, 29671, 29682, 29706, 29739, 29789, 29808, 29846, 29851, 29853, 29860, 29874, 29876, 29892, 29899, 29928, 29949, 29961, 29964, 29975, 30034, 30060, 30081, 30118, 30261, 30279, 30297, 30304, 30349, 30360, 30394, 30396, 30473, 30504, 30505, 30545, 30559, 30561, 30580, 30646, 30669, 30673, 30710, 30720, 30741, 30759, 30786, 30789, 30809, 30850, 30893, 30930, 30936, 30946, 30957, 30979, 31017, 31023, 31025, 31059, 31066, 31135, 31165, 31247, 31253, 31279, 31303, 31326, 31341, 31421, 31424, 31437, 31447, 31451, 31499, 31516, 31540, 31597, 31608, 31619, 31623, 31657, 31717, 31783, 31852, 31856, 31874, 31893, 31948, 31960, 32006, 32011, 32043, 32046, 32047, 32097, 32107, 32129, 32176, 32232, 32264, 32278, 32307, 32314, 32325, 32421, 32441, 32443, 32446, 32475, 32497, 32509, 32640, 32685, 32715, 32755, 32842, 32881, 32907, 32930, 32939, 32992, 33056, 33085, 33152, 33172, 33244, 33261, 33267, 33281, 33307, 33311, 33336, 33338, 33379, 33451, 33478, 33480, 33487, 33498, 33543, 33554, 33593, 33624, 33815, 33828, 33921, 33982, 34053, 34161, 34163, 34199, 34222, 34351, 34494, 34512, 34546, 34553, 34590, 34597, 34601, 34602, 34670, 34718, 34741, 34756, 34769, 34895, 34984, 35087, 35100, 35107, 35123, 35177, 35209, 35251, 35323, 35347, 35361, 35371, 35375, 35376, 35410, 35426, 35557, 35566, 35600, 35604, 35617, 35631, 35664, 35665, 35689, 35706, 35734, 35784, 35786, 35796, 35808, 35851, 35852, 35872, 35937, 35944, 35955, 35959, 35963, 35979, 35986, 36028, 36076, 36095, 36120, 36122, 36124, 36151, 36175, 36211, 36216, 36271, 36289, 36290, 36302, 36314, 36371, 36379, 36381, 36407, 36411, 36435, 36489, 36491, 36495, 36503, 36505, 36548, 36559, 36568, 36584, 36585, 36598, 36670, 36737, 36742, 36748, 36755, 36792, 36812, 36832, 36893, 36910, 36944, 36949, 37015, 37046, 37094, 37105, 37128, 37155, 37170, 37229, 37252, 37280, 37345, 37355, 37383, 37388, 37426, 37437, 37493, 37494, 37503, 37615, 37650, 37652, 37732, 37740, 37793, 37794, 37805, 37810, 37823, 37836, 37855, 37857, 37876, 37882, 37887, 37901, 37932, 37933, 37942, 37956, 37964, 37966, 37986, 37997, 38044, 38049, 38055, 38081, 38085, 38202, 38216, 38322, 38378, 38383, 38438, 38542, 38544, 38571, 38585, 38599, 38696, 38721, 38739, 38781, 38830, 38834, 38838, 38870, 38912, 38922, 38923, 38929, 38932, 38960, 38987, 39012, 39040, 39042, 39063, 39064, 39080, 39098, 39107, 39111, 39116, 39130, 39132, 39151, 39173, 39191, 39220, 39223, 39241, 39244, 39256, 39262, 39270, 39287, 39306, 39317, 39361, 39415, 39439, 39474, 39491, 39493, 39549, 39550, 39590, 39607, 39639, 39654, 39693, 39697, 39794, 39842, 39882, 39884, 39894, 39919, 39927, 39929, 39981, 40000, 40050, 40052, 40070, 40072, 40073, 40078, 40107, 40129, 40164, 40186, 40223, 40272, 40279, 40282, 40287, 40289, 40294, 40302, 40361, 40441, 40467, 40486, 40543, 40556, 40558, 40566, 40569, 40582, 40592, 40651, 40731, 40757, 40782, 40799, 40801, 40849, 40870, 40903, 40949, 40961, 40995, 41003, 41012, 41020, 41027, 41040, 41072, 41080, 41123, 41141, 41146, 41157, 41161, 41177, 41191, 41203, 41217, 41253, 41315, 41321, 41346, 41359, 41361, 41428, 41446, 41447, 41460, 41475, 41526, 41527, 41539, 41595, 41603, 41606, 41632, 41657, 41665, 41672, 41707, 41764, 41776, 41788, 41790, 41813, 41823, 41831, 41894, 42010, 42030, 42040, 42070, 42111, 42114, 42137, 42162, 42224, 42267, 42291, 42295, 42331, 42337, 42340, 42412, 42416, 42417, 42450, 42580, 42603, 42608, 42616, 42723, 42740, 42759, 42773, 42776, 42794, 42805, 42827, 42976, 42999, 43000, 43023, 43036, 43054, 43134, 43157, 43187, 43201, 43234, 43287, 43317, 43365, 43379, 43381, 43387, 43390, 43419, 43535, 43563, 43600, 43612, 43691, 43709, 43827, 43863, 43894, 43898, 43905, 43922, 43934, 44001, 44004, 44034, 44055, 44059, 44125, 44155, 44189, 44194, 44201, 44226, 44347, 44350, 44454, 44469, 44479, 44518, 44568, 44616, 44660, 44672, 44764, 44772, 44831, 44929, 45162, 45183, 45195, 45200, 45202, 45233, 45244, 45253, 45256, 45318, 45423, 45436, 45457, 45476, 45486, 45513, 45588, 45680, 45723, 45725, 45729, 45761, 45815, 45831, 45838, 45880, 45897, 45966, 46061, 46089, 46155, 46173, 46201, 46246, 46318, 46383, 46384, 46388, 46391, 46427, 46442, 46445, 46492, 46494, 46513, 46517, 46535, 46539, 46544, 46554, 46582, 46586, 46597, 46602, 46634, 46650, 46653, 46655, 46660, 46663, 46672, 46706, 46718, 46764, 46805, 46814, 46892, 46895, 46907, 46959, 46998, 47007, 47032, 47051, 47072, 47073, 47078, 47082, 47108, 47112, 47125, 47127, 47139, 47151, 47202, 47211, 47223, 47258, 47260, 47305, 47313, 47380, 47410, 47411, 47489, 47515, 47516, 47535, 47544, 47546, 47566, 47572, 47610, 47618, 47619, 47635, 47698, 47738, 47769, 47803, 47807, 47827, 47868, 47869, 47875, 47884, 47888, 47904, 47906, 47917, 47943, 47953, 47959, 47977, 48030, 48035, 48103, 48125, 48205, 48310, 48314, 48320, 48343, 48362, 48374, 48439, 48478, 48592, 48601, 48607, 48617, 48619, 48666, 48668, 48686, 48694, 48705, 48727, 48740, 48741, 48750, 48760, 48848, 48898, 48902, 48962, 49007, 49023, 49042, 49080, 49084, 49095, 49141, 49148, 49161, 49167, 49177, 49182, 49194, 49213, 49227, 49231, 49232, 49250, 49255, 49263, 49415, 49468, 49478, 49549, 49565, 49570, 49575, 49580, 49597, 49601, 49602, 49626, 49654, 49657, 49664, 49668, 49712, 49720, 49745, 49761, 49762, 49765, 49770, 49777, 49779, 49785, 49819, 49844, 49852, 49854, 49855, 49944, 49992, 49997, 50005, 50011, 50084, 50087, 50090, 50103, 50122, 50164, 50168, 50187, 50188, 50203, 50205, 50230, 50241, 50300, 50330, 50353, 50368, 50375, 50397, 50469, 50522, 50554, 50589, 50595, 50612, 50614, 50617, 50633, 50636, 50642, 50676, 50685, 50687, 50718, 50761, 50777, 50781, 50787, 50790, 50798, 50802, 50806, 50817, 50872, 50921, 50941, 50999, 51026, 51051, 51089, 51130, 51200, 51216, 51225, 51244, 51291, 51314, 51318, 51345, 51346, 51383, 51434, 51490, 51495, 51498, 51516, 51536, 51541, 51555, 51559, 51587, 51593, 51641, 51645, 51654, 51670, 51690, 51694, 51702, 51741, 51745, 51747, 51767, 51774, 51802, 51841, 51865, 51871, 51905, 51917, 51941, 51982, 52029, 52038, 52046, 52054, 52075, 52079, 52141, 52148, 52150, 52169, 52185, 52220, 52263, 52266, 52304, 52363, 52374, 52378, 52379, 52396, 52465, 52467, 52509, 52582, 52597, 52697, 52724, 52727, 52733, 52743, 52751, 52777, 52864, 52934, 53002, 53017, 53030, 53078, 53098, 53181, 53196, 53223, 53245, 53306, 53337, 53353, 53356, 53378, 53380, 53389, 53424, 53438, 53503, 53514, 53581, 53654, 53678, 53684, 53688, 53710, 53724, 53744, 53763, 53772, 53777, 53793, 53824, 53825, 53831, 53846, 53890, 53917, 53931, 53938, 53940, 53955, 54007, 54103, 54137, 54153, 54179, 54182, 54203, 54217, 54271, 54300, 54337, 54338, 54435, 54436, 54484, 54607, 54613, 54661, 54675, 54676, 54685, 54710, 54731, 54736, 54754, 54757, 54758, 54797, 54832, 54886, 54933, 54937, 54981, 54987, 55053, 55090, 55117, 55135, 55160, 55336, 55351, 55365, 55395, 55429, 55494, 55514, 55542, 55645, 55669, 55735, 55758, 55775, 55785, 55813, 55888, 55932, 55977, 55994, 56017, 56018, 56022, 56068, 56086, 56095, 56097, 56128, 56137, 56140, 56154, 56166, 56177, 56230, 56234, 56305, 56350, 56360, 56458, 56475, 56487, 56525, 56542, 56548, 56561, 56576, 56689, 56696, 56704, 56739, 56814, 56830, 56906, 56916, 56969, 56990, 57078, 57090, 57095, 57100, 57133, 57185, 57197, 57218, 57297, 57348, 57362, 57368, 57393, 57441, 57453, 57624, 57644, 57646, 57666, 57698, 57699, 57723, 57727, 57745, 57746, 57834, 57887, 57892, 57898, 57901, 57902, 57961, 57991, 58057, 58089, 58104, 58116, 58125, 58174, 58187, 58247, 58263, 58279, 58312, 58350, 58357, 58369, 58400, 58418, 58506, 58529, 58563, 58578, 58581, 58599, 58609, 58612, 58624, 58647, 58672, 58675, 58735, 58751, 58762, 58798, 58810, 58828, 58886, 58935, 58938, 58952, 58999, 59071, 59088, 59137, 59148, 59149, 59156, 59193, 59195, 59197, 59203, 59211, 59213, 59214, 59215, 59240, 59261, 59286, 59295, 59300, 59306, 59317, 59377, 59384, 59398, 59402, 59407, 59494, 59503, 59588, 59633, 59634, 59671, 59720, 59792, 59870, 59900, 59931, 59946, 59951, 59980, 59998, 60032, 60045, 60075, 60102, 60134, 60141, 60175, 60187, 60242, 60246, 60275, 60294, 60340, 60377, 60406, 60467, 60508, 60571, 60573, 60599, 60605, 60653, 60681, 60683, 60686, 60687, 60700, 60726, 60756, 60836, 60895, 60921, 60924, 60930, 60932, 60972, 60986, 61004, 61131, 61162, 61190, 61229, 61301, 61303, 61316, 61340, 61384, 61387, 61406, 61428, 61445, 61551, 61577, 61638, 61651, 61655, 61670, 61709, 61730, 61760, 61778, 61811, 61821, 61850, 61851, 61889, 61898, 61911, 61917, 61988, 62005, 62012, 62062, 62074, 62092, 62184, 62209, 62235, 62289, 62309, 62373, 62534, 62552, 62575, 62595, 62627, 62676, 62702, 62719, 62736, 62784, 62790, 62855, 62893, 62896, 62899, 62968, 62987, 63031, 63047, 63097, 63154, 63197, 63263, 63352, 63367, 63432, 63438, 63439, 63485, 63509, 63510, 63556, 63564, 63660, 63661, 63720, 63800, 63807, 63897, 63908, 63929, 63940, 63959, 64003, 64151, 64204, 64214, 64227, 64236, 64239, 64241, 64261, 64297, 64306, 64313, 64398, 64408, 64439, 64442, 64475, 64496, 64527, 64529, 64591, 64792, 64806, 64846, 64886, 64933, 65074, 65092, 65105, 65129, 65137, 65175, 65223, 65239, 65245, 65250, 65268, 65273, 65286, 65292, 65305, 65313, 65338, 65355, 65372, 65376, 65412, 65441, 65468, 65505, 65509, 65519, 65538, 65541, 65552, 65635, 65657, 65698, 65702, 65705, 65711, 65771, 65790, 65811, 65818, 65822, 65836, 65859, 65860, 65862, 65888, 65924, 65934, 65946, 65971, 65983, 65998, 66002, 66013, 66042, 66071, 66072, 66081, 66099, 66101, 66102, 66132, 66156, 66187, 66194, 66199, 66220, 66221, 66256, 66264, 66281, 66292, 66320, 66345, 66354, 66358, 66404, 66408, 66424, 66430, 66442, 66449, 66492, 66535, 66551, 66564, 66652, 66679, 66683, 66689, 66700, 66716, 66720, 66722, 66725, 66729, 66750, 66757, 66763, 66775, 66781, 66790, 66799, 66822, 66845, 66848, 66850, 66866, 66883, 66888, 66889, 66935, 66937, 66986, 66995, 67011, 67019, 67026, 67028, 67077, 67105, 67129, 67167, 67174, 67178, 67213, 67216, 67218, 67230, 67231, 67276, 67300, 67340, 67363, 67369, 67383, 67399, 67419, 67431, 67439, 67446, 67455, 67458, 67462, 67464, 67478, 67494, 67504, 67524, 67568, 67618, 67625, 67647, 67651, 67670, 67675, 67686, 67732, 67749, 67785, 67793, 67807, 67815, 67821, 67830, 67848, 67863, 67883, 67886, 67922, 67931, 67952, 67961, 67962, 67963, 67984, 67999, 68009, 68048, 68050, 68060, 68062, 68069, 68071, 68074, 68105, 68123, 68151, 68153, 68160, 68168, 68173, 68175, 68178, 68181, 68211, 68221, 68223, 68225, 68232, 68247, 68255, 68314, 68336, 68345, 68368, 68376, 68377, 68379, 68390, 68417, 68421, 68424, 68450, 68457, 68482, 68518, 68551, 68568, 68577, 68586, 68590, 68606, 68658, 68718, 68807, 68851, 68878, 68920, 68947, 68955, 68960, 68989, 68994, 69025, 69047, 69096, 69134, 69182, 69209, 69223, 69241, 69279, 69315, 69324, 69334, 69351, 69389, 69415, 69459, 69491, 69529, 69556, 69562, 69567, 69583, 69591, 69592, 69616, 69617, 69628, 69703, 69707, 69716, 69725, 69764, 69787, 69817, 69820, 69836, 69839, 69865, 69867, 69884, 69907, 69920, 69932, 69940, 69944, 69965, 69997, 70023, 70065, 70079, 70125, 70177, 70199, 70207, 70209, 70216, 70224, 70225, 70261, 70270, 70319, 70405, 70442, 70462, 70493, 70538, 70578, 70583, 70652, 70750, 70794, 70798, 70812, 70814, 70819, 70845, 70909, 70926, 70930, 70936, 70968, 70977, 70983, 70987, 70989, 71004, 71016, 71050, 71067, 71070, 71071, 71083, 71097, 71108, 71135, 71140, 71194, 71265, 71304, 71318, 71321, 71333, 71339, 71344, 71346, 71349, 71386, 71393, 71403, 71443, 71455, 71463, 71466, 71478, 71482, 71486, 71540, 71543, 71594, 71604, 71608, 71619, 71632, 71654, 71671, 71694, 71742, 71759, 71767, 71829, 71848, 71860, 71862, 71866, 71899, 71932, 71947, 71972, 72000, 72022, 72024, 72046, 72054, 72062, 72068, 72116, 72119, 72127, 72140, 72148, 72172, 72236, 72252, 72273, 72288, 72299, 72339, 72349, 72359, 72385, 72397, 72404, 72417, 72432, 72491, 72513, 72544, 72546, 72560, 72565, 72567, 72643, 72649, 72652, 72681, 72689, 72694, 72696, 72702, 72727, 72743, 72758, 72766, 72774, 72784, 72801, 72803, 72819, 72874, 72905, 72921, 72932, 72945, 72951, 72955, 72961, 72974, 72990, 72997, 73013, 73018, 73022, 73030, 73033, 73038, 73040, 73052, 73066, 73077, 73093, 73104, 73107, 73142, 73159, 73187, 73189, 73192, 73219, 73267, 73269, 73281, 73323, 73333, 73346, 73348, 73356, 73374, 73389, 73409, 73410, 73419, 73440, 73477, 73480, 73483, 73499, 73530, 73556, 73559, 73581, 73596, 73602, 73621, 73638, 73650, 73660, 73682, 73713, 73726, 73749, 73756, 73776, 73783, 73785, 73828, 73847, 73851, 73853, 73874, 73876, 73912, 73922, 73940, 73941, 73944, 73946, 73963, 73964, 73967, 73989, 74001, 74003, 74047, 74083, 74137, 74151, 74155, 74159, 74162, 74172, 74198, 74199, 74238, 74246, 74270, 74277, 74283, 74307, 74351, 74377, 74389, 74408, 74409, 74450, 74451, 74453, 74455, 74458, 74463, 74487, 74492, 74497, 74510, 74539, 74569, 74572, 74573, 74582, 74625, 74635, 74659, 74680, 74721, 74743, 74748, 74752, 74765, 74766, 74805, 74820, 74826, 74867, 74894, 74898, 74904, 74910, 74927, 74940, 74942, 74945, 74949, 74955, 74957, 74960, 75013, 75024, 75026, 75030, 75039, 75044, 75082, 75088, 75113, 75152, 75159, 75185, 75212, 75236, 75315, 75337, 75378, 75403, 75410, 75420, 75469, 75471, 75487, 75498, 75530, 75545, 75583, 75597, 75599, 75603, 75607, 75627, 75635, 75636, 75655, 75659, 75672, 75707, 75728, 75739, 75742, 75777, 75816, 75835, 75838, 75872, 75900, 75902, 75908, 75919, 75975, 75976, 75997, 75999, 76011, 76020, 76037, 76084, 76120, 76164, 76182, 76193, 76197, 76224, 76258, 76276, 76305, 76309, 76320, 76394, 76395, 76397, 76431, 76436, 76450, 76485, 76491, 76507, 76527, 76538, 76555, 76607, 76614, 76643, 76648, 76649, 76659, 76664, 76677, 76714, 76716, 76736, 76746, 76768, 76771, 76784, 76802, 76806, 76824, 76840, 76847, 76860, 76863, 76886, 76911, 76924, 76944, 76951, 76954, 76959, 76971, 76993, 77034, 77047, 77067, 77069, 77105, 77117, 77136, 77137, 77173, 77198, 77202, 77206, 77228, 77281, 77289, 77405, 77410, 77415, 77429, 77446, 77461, 77481, 77519, 77520, 77521, 77524, 77527, 77537, 77572, 77577, 77587, 77595, 77597, 77616, 77621, 77664, 77698, 77723, 77748, 77753, 77790, 77792, 77795, 77799, 77806, 77809, 77831, 77846, 77867, 77889, 77891, 77962, 77968, 77994, 78011, 78084, 78085, 78173, 78202, 78204, 78217, 78263, 78286, 78296, 78305, 78316, 78367, 78369, 78370, 78405, 78445, 78455, 78607, 78613, 78615, 78625, 78628, 78644, 78645, 78654, 78712, 78740, 78825, 78847, 78889, 78893, 78902, 78906, 78934, 78943, 78992, 79000, 79027, 79033, 79089, 79113, 79125, 79143, 79147, 79177, 79197, 79240, 79250, 79268, 79303, 79338, 79367, 79393, 79405, 79443, 79467, 79535, 79589, 79630, 79647, 79687, 79688, 79722, 79747, 79792, 79803, 79813, 79836, 79858, 79889, 79936, 79954, 79964, 80024, 80048, 80057, 80070, 80087, 80090, 80117, 80136, 80162, 80170, 80227, 80256, 80295, 80299, 80347, 80499, 80542, 80554, 80576, 80594, 80680, 80688, 80755, 80773, 80780, 80783, 80788, 80791, 80817, 80834, 80861, 80863, 80949, 80973, 81001, 81085, 81104, 81123, 81180, 81187, 81270, 81272, 81364, 81369, 81391, 81404, 81414, 81424, 81435, 81513, 81544, 81570, 81580, 81588, 8

/opt/anaconda3/envs/cosc410_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py:685: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

Prediction Progress: 100%|██████████| 1306/1306 [14:34:20<00:00, 40.17s/it]

tensor([0.9985, 0.9899, 0.9977,  ..., 0.9976, 0.9958, 0.9985])
tensor([1, 1, 1,  ..., 1, 1, 1])
83522
------------------------

Map:   0%|          | 0/83522 [00:00<?, ? examples/s]

Unlabeled Samples Remaining:  99%|█████████▊| 24735/25056 [52:49:56<57:08, 10.68s/it]

Indices where the condition was met: [199, 912, 1046, 1429, 1569, 1835, 2368, 3606, 3804, 4029, 4292, 4296, 4299, 4309, 4320, 4351, 4400, 4453, 4543, 4563, 4638, 4792, 4939, 5032, 5067, 5093, 5134, 5190, 5220, 5713, 5761, 5788, 6078, 6538, 6581, 6615, 6632, 6670, 6816, 6846, 6847, 7903, 8083, 8084, 8230, 8772, 8900, 9217, 9624, 10387, 10450, 10791, 11054, 11120, 11279, 11313, 11624, 11673, 11869, 11966, 12235, 12236, 12382, 12400, 12455, 12535, 12605, 12639, 12670, 12791, 12836, 12976, 13289, 13378, 13534, 13765, 13939, 13969, 14047, 14234, 14371, 14671, 14747, 14750, 14801, 14842, 14864, 14880, 14928, 15090, 15148, 15304, 15345, 16684, 17107, 17268, 17339, 18219, 18375, 18640, 18993, 19042, 19089, 19103, 19174, 19992, 20425, 20443, 20843, 21539, 21980, 22120, 22373, 22575, 22580, 22592, 22641, 22685, 22953, 23034, 23127, 23189, 23288, 23366, 23459, 23693, 23767, 23785, 23790, 23900, 23964, 24272, 24399, 24837, 24910, 24936, 25154, 25305, 25756, 25775, 25934, 26231, 26278, 26522, 27057, 27224, 27283, 27388, 27416, 27543, 27639, 27735, 27823, 27872, 27912, 27925, 28195, 28199, 28410, 28623, 28694, 28802, 29046, 29519, 29563, 29764, 29996, 30035, 30372, 30441, 30443, 30485, 30573, 30654, 30727, 30775, 30788, 30817, 31067, 31239, 31396, 31525, 31564, 31943, 32833, 32915, 32984, 33344, 33697, 33835, 33861, 33926, 33959, 34025, 34055, 34090, 34145, 34336, 34367, 34457, 34798, 34839, 35121, 35237, 35248, 35289, 35395, 35411, 35834, 35840, 36002, 36241, 36279, 36287, 36501, 36517, 36609, 36668, 36726, 36882, 37005, 37080, 37193, 37326, 37359, 37457, 37669, 37765, 37988, 38051, 38357, 38393, 38424, 38435, 38518, 38527, 38631, 38794, 38930, 38944, 38982, 38984, 39006, 39217, 39248, 39285, 39299, 39360, 39531, 39571, 39596, 39709, 39839, 39856, 40004, 40011, 40145, 40379, 40495, 40571, 40733, 40827, 40959, 40980, 41043, 41071, 41214, 41263, 41287, 41468, 41768, 41883, 41932, 41960, 41996, 42069, 42091, 42098, 42171, 42182, 42272, 42449, 42554, 42556, 42716, 42738, 42985, 43269, 43289, 43346, 43352, 43395, 43397, 43502, 43540, 43589, 43757, 43799, 43883, 44026, 44192, 44283, 44302, 44304, 44348, 44415, 44492, 44572, 44625, 44881, 45014, 45408, 45960, 46030, 46303, 46389, 46463, 46567, 46591, 46616, 46669, 46682, 46816, 47060, 47141, 47192, 47239, 47282, 47368, 47594, 47612, 47621, 47623, 47643, 47699, 47847, 47969, 48056, 48089, 48173, 48483, 48560, 48594, 48648, 48828, 48889, 49008, 49030, 49043, 49126, 49129, 49220, 49301, 49312, 49376, 49505, 49514, 49531, 49546, 49555, 49696, 49890, 49958, 50172, 50216, 50337, 50351, 50362, 50577, 50690, 50697, 50704, 50911, 50927, 50990, 51075, 51128, 51197, 51463, 51826, 51933, 51939, 52688, 52709, 52791, 52793, 52794, 52865, 52891, 52962, 53026, 53109, 53220, 53367, 53672, 53733, 53739, 53891, 53901, 53922, 54034, 54062, 54200, 54282, 54336, 54421, 54593, 54659, 54660, 54756, 54944, 54997, 55520, 55642, 55714, 56020, 56049, 56122, 56124, 56178, 56271, 56409, 56423, 56535, 56678, 56691, 56757, 56771, 56889, 56997, 57239, 57276, 57283, 57304, 57375, 57408, 57424, 57477, 57651, 57793, 57822, 57874, 57881, 58027, 58051, 58268, 58272, 58345, 58497, 58522, 58566, 58597, 58785, 59101, 59216, 59436, 59742, 59800, 59974, 60020, 60024, 60055, 60154, 60168, 60199, 60350, 60493, 60527, 60632, 60945, 61007, 61328, 61506, 61512, 61569, 61733, 61801, 62076, 62503, 62550, 62776, 63024, 63157, 63211, 63245, 63383, 63437, 63444, 63453, 63479, 63688, 63699, 63765, 63801, 63825, 63826, 63902, 64064, 64213, 64250, 64327, 64625, 64650, 64738, 64758, 64901, 64972, 65005, 65197, 65215, 65345, 65404, 65452, 65494, 65507, 65544, 65606, 65630, 65647, 65678, 65787, 65797, 65801, 65806, 65821, 65900, 66014, 66092, 66108, 66172, 66222, 66351, 66373, 66429, 66484, 66496, 66674, 66859, 66936, 66981, 67000, 67052, 67131, 67280, 67344, 67425, 67461, 67544, 67676, 67682, 67762, 67817, 67902, 68241, 68324, 68358, 68595, 68692, 68719, 68870, 68886, 68917, 68937, 68954, 68991, 69007, 69014, 69130, 69166, 69207, 69249, 69270, 69337, 69484, 69509, 69803, 69812, 69851, 69871, 69918, 70044, 70073, 70114, 70134, 70142, 70439, 70490, 70621, 70686, 70898, 70978, 71011, 71021, 71160, 71261, 71294, 71335, 71790, 71798, 71824, 71931, 72025, 72109, 72187, 72283, 72303, 72369, 72407, 72452, 72466, 72473, 72487, 72576, 72595, 72631, 72805, 72827, 72833, 72886, 73215, 73378, 73399, 73487, 73557, 73609, 73644, 73692, 73716, 73787, 73833, 73881, 73882, 73978, 74007, 74056, 74058, 74173, 74290, 74554, 74556, 74959, 74966, 75028, 75139, 75174, 75190, 75249, 75252, 75271, 75272, 75335, 75391, 75482, 75523, 75526, 75585, 75664, 75787, 75865, 75885, 75906, 75917, 76074, 76096, 76170, 76174, 76229, 76237, 76253, 76289, 76350, 76372, 76383, 76417, 76425, 76437, 76505, 76585, 76617, 76927, 77042, 77132, 77143, 77193, 77272, 77304, 77329, 77372, 77376, 77480, 77516, 77567, 77699, 77742, 77768, 78050, 78221, 78312, 78354, 78358, 78518, 78609, 78627, 78651, 78656, 78674, 78678, 78761, 78883, 78939, 79003, 79015, 79169, 79287, 79500, 79742, 79814, 79852, 79946, 79966, 79998, 80000, 80085, 80206, 80232, 80268, 80288, 80545, 80582, 80663, 80806, 80890, 81005, 81301, 81397, 81418, 81440, 81446, 81680, 81785, 81896, 82076, 82104, 82187, 82287, 82399, 82423, 82436, 82480, 82514, 82634, 82772, 82790, 82967]

/opt/anaconda3/envs/cosc410_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py:685: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

Prediction Progress: 100%|██████████| 1306/1306 [14:42:40<00:00, 40.55s/it]

tensor([0.9981, 0.9976, 0.9979,  ..., 0.9976, 0.9932, 0.9981])
tensor([1, 1, 1,  ..., 1, 1, 1])
83522
------------------------

Map:   0%|          | 0/83522 [00:00<?, ? examples/s]

Unlabeled Samples Remaining:  99%|█████████▉| 24897/25056 [70:58:29<46:19, 17.48s/it]

Indices where the condition was met: [3453, 4469, 5069, 5157, 5774, 6241, 6862, 7489, 11772, 12860, 14496, 15286, 16106, 16128, 16275, 18048, 18484, 18921, 19601, 19612, 21151, 22187, 22219, 23115, 23596, 23705, 24683, 25041, 25572, 26264, 29431, 30532, 32361, 32919, 34282, 35355, 35919, 36232, 36978, 37568, 37753, 37844, 37993, 38190, 38458, 38651, 38797, 39238, 39429, 39461, 39651, 39954, 41256, 41766, 42485, 42548, 43266, 43571, 44498, 44914, 45286, 46729, 46912, 47079, 47444, 47597, 48842, 49115, 49191, 49198, 49248, 49513, 49532, 49678, 50412, 50742, 51428, 51664, 51902, 52161, 52295, 52581, 52732, 52937, 52957, 53265, 53509, 55304, 56558, 58511, 58555, 58745, 59192, 59305, 59403, 59981, 60049, 60231, 60498, 61035, 61264, 64413, 65141, 65515, 65792, 65954, 66316, 66413, 66529, 66825, 67460, 67512, 67598, 67602, 67644, 67694, 68124, 68179, 68634, 68773, 69113, 69741, 69973, 70341, 70510, 70775, 70848, 71088, 71337, 71557, 72093, 72523, 72600, 73101, 73248, 73311, 73315, 74378, 74433, 74764, 74825, 74935, 75053, 75107, 75261, 75359, 75529, 76492, 76578, 76629, 76720, 76772, 76787, 77050, 77126, 77299, 77778, 78920, 79071, 80354, 80414, 82532]

/opt/anaconda3/envs/cosc410_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py:685: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

Prediction Progress: 100%|██████████| 1306/1306 [14:46:08<00:00, 40.71s/it]

tensor([0.9977, 0.9975, 0.9976,  ..., 0.9969, 0.9976, 0.9979])
tensor([1, 1, 1,  ..., 1, 1, 1])
83522
------------------------

Map:   0%|          | 0/83522 [00:00<?, ? examples/s]

Unlabeled Samples Remaining: 100%|█████████▉| 24951/25056 [89:08:49<47:41, 27.26s/it]

Indices where the condition was met: [173, 3821, 3918, 6817, 8570, 13340, 14822, 15890, 16471, 16877, 17258, 17313, 22779, 23340, 24933, 28777, 30263, 30491, 31098, 31746, 34908, 35987, 36259, 41204, 43854, 47464, 47859, 48083, 48422, 49014, 50578, 50914, 51531, 52199, 60193, 64547, 64892, 67345, 67655, 67837, 68245, 68763, 69107, 69744, 69842, 71867, 73060, 75408, 75581, 75878, 80662, 81553, 81806, 82862]

/opt/anaconda3/envs/cosc410_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py:685: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

Prediction Progress: 100%|██████████| 1306/1306 [14:35:26<00:00, 40.22s/it]

tensor([0.9973, 0.9979, 0.9983,  ..., 0.9963, 0.9963, 0.9983])
tensor([1, 1, 1,  ..., 1, 1, 1])
83522
------------------------

Map:   0%|          | 0/83522 [00:00<?, ? examples/s]

Unlabeled Samples Remaining: 100%|█████████▉| 24973/25056 [107:31:34<57:15, 41.39s/it]

Indices where the condition was met: [4952, 5145, 5260, 14148, 19735, 21060, 27870, 34077, 37999, 42206, 43601, 45977, 48381, 50456, 50873, 51311, 64655, 65817, 66089, 66261, 71029, 76525]

/opt/anaconda3/envs/cosc410_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py:685: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

Prediction Progress: 100%|██████████| 1306/1306 [14:39:21<00:00, 40.40s/it]

tensor([0.9977, 0.9973, 0.9980,  ..., 0.9966, 0.9980, 0.9976])
tensor([1, 1, 1,  ..., 1, 1, 1])
83522
------------------------

Map:   0%|          | 0/83522 [00:00<?, ? examples/s]

Unlabeled Samples Remaining: 100%|█████████▉| 24991/25056 [125:43:52<1:06:19, 61.22s/it]

Indices where the condition was met: [27690, 33660, 43828, 46982, 47098, 53820, 61664, 66001, 66912, 67567, 67776, 68481, 70433, 70634, 73575, 73578, 76992, 78456]

/opt/anaconda3/envs/cosc410_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py:685: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

Prediction Progress: 100%|██████████| 1306/1306 [14:08:48<00:00, 39.00s/it]

tensor([0.9979, 0.9978, 0.9980,  ..., 0.9952, 0.9976, 0.9976])
tensor([1, 1, 1,  ..., 1, 1, 1])
83522
------------------------

Map:   0%|          | 0/83522 [00:00<?, ? examples/s]

Indices where the condition was met: []

/opt/anaconda3/envs/cosc410_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py:685: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

Prediction Progress: 100%|██████████| 1306/1306 [14:23:07<00:00, 39.65s/it]

tensor([0.9968, 0.9982, 0.9984,  ..., 0.9938, 0.9981, 0.9976])
tensor([1, 1, 1,  ..., 1, 1, 1])
83522
------------------------

Map:   0%|          | 0/83522 [00:00<?, ? examples/s]

Unlabeled Samples Remaining: 100%|█████████▉| 24998/25056 [161:11:16<1:52:48, 116.70s/it]

Indices where the condition was met: [51552, 57162, 71092, 73910, 74020, 76996, 81852]

/opt/anaconda3/envs/cosc410_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py:685: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

Prediction Progress: 100%|██████████| 1306/1306 [14:22:03<00:00, 39.60s/it]

tensor([0.9971, 0.9966, 0.9978,  ..., 0.9949, 0.9972, 0.9966])
tensor([1, 1, 1,  ..., 1, 1, 1])
83522
------------------------

Map:   0%|          | 0/83522 [00:00<?, ? examples/s]

Unlabeled Samples Remaining: 100%|█████████▉| 25031/25056 [179:03:02<1:03:59, 153.60s/it]

Indices where the condition was met: [1169, 6167, 9385, 21778, 26741, 27938, 28274, 45993, 47942, 48508, 48536, 49691, 50171, 50773, 54742, 55498, 56184, 58874, 59153, 61814, 65816, 67881, 69138, 69587, 69819, 69893, 70009, 70840, 71369, 73017, 73051, 75775, 76293]

/opt/anaconda3/envs/cosc410_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py:685: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

Prediction Progress: 100%|██████████| 1306/1306 [14:20:16<00:00, 39.52s/it]

tensor([0.9951, 0.9955, 0.9958,  ..., 0.9957, 0.9960, 0.9958])
tensor([1, 1, 1,  ..., 1, 1, 1])
83522
------------------------

Map:   0%|          | 0/83522 [00:00<?, ? examples/s]

Unlabeled Samples Remaining: 100%|█████████▉| 25053/25056 [196:46:10<10:15, 205.28s/it]

Indices where the condition was met: [5096, 16647, 23470, 67854, 68840, 69753, 72272, 72518, 73070, 73099, 73589, 74523, 75336, 75764, 76281, 76679, 76962, 77019, 77022, 77221, 77274, 77397]

/opt/anaconda3/envs/cosc410_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py:685: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

Prediction Progress: 100%|██████████| 1306/1306 [14:26:45<00:00, 39.82s/it]

tensor([0.9966, 0.9968, 0.9969,  ..., 0.9957, 0.9968, 0.9963])
tensor([1, 1, 1,  ..., 1, 1, 1])
83522
------------------------

Map:   0%|          | 0/83522 [00:00<?, ? examples/s]

Indices where the condition was met: []

/opt/anaconda3/envs/cosc410_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py:685: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

Prediction Progress: 100%|██████████| 1306/1306 [14:34:11<00:00, 40.16s/it]

tensor([0.9933, 0.9934, 0.9935,  ..., 0.9930, 0.9933, 0.9935])
tensor([1, 1, 1,  ..., 1, 1, 1])
83522
------------------------

Map:   0%|          | 0/83522 [00:00<?, ? examples/s]

Unlabeled Samples Remaining: 100%|██████████| 25056/25056 [232:46:15<00:00, 362.36s/it]

Indices where the condition was met: [58925, 69625, 75283]

/opt/anaconda3/envs/cosc410_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py:685: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

Unlabeled Samples Remaining: 100%|██████████| 25056/25056 [236:18:38<00:00, 33.95s/it]

All labels are filled. Stopping training.

1

Evaluation Results on Test Data:
Accuracy:  0.9040948275862069
Precision: 0.8941426768586276
Recall:    0.8868404755714969